backend/src/main/java/com/funeat/category/domain/Category.java
backend/src/main/java/com/funeat/category/domain/CategoryType.java
backend/src/main/java/com/funeat/member/domain/Gender.java
backend/src/main/java/com/funeat/member/domain/Member.java
backend/src/main/java/com/funeat/member/domain/bookmark/ProductBookmark.java
backend/src/main/java/com/funeat/member/domain/bookmark/RecipeBookmark.java
backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
backend/src/main/java/com/funeat/product/domain/Product.java
backend/src/main/java/com/funeat/product/domain/ProductRecipe.java
backend/src/main/java/com/funeat/recipe/domain/Recipe.java
backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
backend/src/main/java/com/funeat/review/domain/Review.java
backend/src/main/java/com/funeat/review/domain/ReviewTag.java
backend/src/main/java/com/funeat/tag/domain/Tag.java

- close #7 
- 펀잇팀 서비스에 필요한 모든 엔티티를 설계하고 구현함.
- X
- X

[BE] feat: 전체 엔티티 설계 및 구현

---

frontend/.storybook/preview.ts
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/index.tsx
frontend/src/mocks/browser.ts
frontend/src/mocks/handlers.ts
frontend/tsconfig.json
frontend/yarn.lock

[FE] chore: msw 설정

---

frontend/package.json
frontend/src/index.tsx
frontend/yarn.lock

- close #36 
- 배포한 디자인 시스템을 설치하고 적용하였습니다.
x
x

[FE] chore: 디자인 시스템 설치 및 적용

---

frontend/src/index.tsx
frontend/tsconfig.json
frontend/webpack.common.js

- close #49
- 절대경로를 `@components` -> `@/components/*`로 변경
x
- 힘들어요

[FE] chore: 절대경로를 '@'에서 '@/'로 변경

---

frontend/package.json
frontend/src/components/Common/Title/Title.stories.tsx
frontend/src/components/Common/Title/Title.tsx
frontend/yarn.lock

- close #31
- 상품 리스트 페이지 타이틀 컴포넌트 추가하였습니다.
x
- router dom 추가 후 뒤로 가는 버튼 추가해야 합니다.

[FE] feat: 상품 리스트 페이지 타이틀 컴포넌트 추가

---

frontend/src/components/Common/SortOptionList/SortOptionList.stories.tsx

- close #79 
- SortOptionList 스토리 prop 타입 에러 수정
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: SortOptionList 스토리 prop 타입 에러 수정

---

backend/src/test/resources/application.yml

- close #87 
- spring.datasource.url -> MODE=MySQL 추가로 테스트 성공을 확인했습니다.
- x
- x

[BE] fix: datasource url 수정으로 테스트 통과 수정

---

backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

- close #85 
- 젠킨스에서 환경변수 할당 시 `-`을 사용하면 쉘 동작 시 오류 가능성이 있어서 `_`로 수정
- 추정 시간 : 1h
- 걸린 시간 : 30m

[BE] refactor: 환경변수에 언더스코어 적용

---

frontend/src/components/Review/ReviewRankingItem/ReviewRankingItem.tsx
frontend/src/pages/HomePage.tsx

- close #99
- favorite -> favoriteFilled로 아이콘 수정
- '전체보기' 텍스트 옆 아이콘 추가
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분

[FE] feat: svg icon 수정

---

frontend/src/components/Review/StarRate/StarRate.stories.tsx
frontend/src/components/Review/StarRate/StarRate.tsx
frontend/src/hooks/useStarRate.ts

- close #107 
별점 컴포넌트를 구현하였습니다.
커스텀 훅으로 분리하였습니다.
Review 폴더안에 넣으면 될까요??
x
- 추정 시간 : 4시간
- 걸린 시간 : 1시간 30분

[FE] feat: 별점 컴포넌트 구현

---

frontend/.gitignore
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/apis/ApiClient.ts
frontend/src/apis/fetch.ts
frontend/src/apis/index.ts
frontend/src/components/Product/ProductItem/ProductItem.stories.tsx
frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
frontend/src/hooks/product/index.ts
frontend/src/hooks/product/useCategory.ts
frontend/src/hooks/useGet.ts
frontend/src/hooks/useMutate.ts
frontend/src/pages/HomePage.tsx
frontend/webpack.common.js
frontend/yarn.lock

- close #121 
- `ApiClient` 클래스 생성
- fetch 함수 작성
- `useCategory` 훅을 만들어서 api 연결 테스트
- useGet은 잘 사용되는 것을 확인했는데 아직 useMutate는 사용해보지 못했습니다. useGet은 get 메서드, useMutate는 post, delete, patch등의 요청으로 사용할 예정입니다.
x
- 추정 시간 : 1시간
- 걸린 시간 : 3시간

[FE] feat: api 기본 설정 및 카테고리 api 연결

---

backend/src/main/java/com/funeat/product/domain/Product.java
backend/src/main/java/com/funeat/review/application/ReviewService.java
backend/src/main/java/com/funeat/review/domain/Review.java
backend/src/main/java/com/funeat/review/presentation/ReviewController.java
backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewDto.java
backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
backend/src/test/java/com/funeat/product/domain/ProductTest.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java

- close #84 
- 리뷰 작성 시, 이미지 업로드는 필수가 아니어서 분기처리 추가
- 리뷰 작성 시, 카운트 쿼리를 통해 해당 상품의 리뷰 카운트를 가져와 평균 평점 계산 추가
- x
- x
- 추정 시간 : 6
- 걸린 시간 : 4

[BE] feat: 이미지 업로드 분기처리, 상품 평균 평점 기능 구현

---

backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
backend/src/main/java/com/funeat/review/presentation/ReviewController.java

- close #127 
- 삭제한 부분 충돌 해결 중 실수로 빼먹은 부분 수정
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: productId 삭제한거 충돌로 build 실패 수정

---

backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
backend/src/main/java/com/funeat/review/presentation/ReviewController.java
backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java

- close #131 
- 리뷰 요청 변경된 부분 테스트 수정 안한 곳 수정
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: 리뷰 평점 요청 1점대로 수정한 부분 테스트 수정

---

backend/src/main/java/com/funeat/member/domain/Gender.java
backend/src/main/java/com/funeat/member/domain/Member.java
backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java

- close #125 
- Member의 age, gender, phoneNumber를 삭제했습니다.
x
x
- 추정 시간 : 0.5
- 걸린 시간 : 0.1

[BE] refactor: 멤버의 나이, 성별, 전화번호 삭제

---

frontend/src/apis/index.ts
frontend/src/hooks/product/index.ts
frontend/src/hooks/product/useProductDetail.ts
frontend/src/mocks/handlers/productHandlers.ts
frontend/src/pages/ProductDetailPage.tsx

- close #136 
- useProductDetail 커스텀 훅 작성
x
- 상품 상세 요청 목 핸들러 예외처리 및 아이디에 맞게 가져오도록 수정했습니다.
- 추정 시간 : 2시간

[FE] feat: 상품 상세 조회 API 연결

---

backend/src/main/java/com/funeat/review/domain/Review.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java

- close #77
- 리뷰에 생성 시간 필드를 추가했습니다.
- 리뷰를 작성하는 Service 테스트에 생성 시간 테스트를 추가했습니다.
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 0.1

[BE] feat: 리뷰 생성 시간 필드 추가

---

frontend/src/pages/ProductDetailPage.tsx

- close #168 
- 리뷰 작성 폼 시트와 정렬 옵션 시트가 정상적으로 열리지 않는 에러를 해결했습니다.
x
x
- 추정 시간 : x

[FE] fix: 바텀시트 오류 해결

---

frontend/package.json
frontend/src/hooks/useGet.ts

- close #177 
- useGet 파라미터 타입 에러 수정
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: useGet 파라미터 타입 에러 수정

---

backend/src/main/java/com/funeat/common/WebConfig.java

- close #192
- CORS 헤더를 모두 허용함
- x
- x
- 추정 시간 : x
- 걸린 시간 : x

[BE] fix: CORS에서 모든 헤더를 열어주는 것으로 수정

---

backend/src/main/java/com/funeat/auth/presentation/AuthController.java
backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java

- close #194 
- 로그인에 /api를 추가합니다.
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.01

[BE] refactor: 로그인 url 변경

---

backend/src/main/java/com/funeat/auth/presentation/AuthController.java
backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java

- close #197
- GET -> POST (이슈 참조)
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] refactor: get 요청에서 post 요청으로 변경

---

backend/src/main/java/com/funeat/member/application/MemberService.java

- close #200 
- 트랜잭션 옵션 수정
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: 회원을 등록할 때, 새로운 트랜잭션에서 수행되도록 수정

---

backend/src/main/java/com/funeat/auth/application/AuthService.java
backend/src/main/java/com/funeat/member/application/MemberService.java

- close #202 
- read only 옵션 제거
- 현재 read only 옵션 제거하는 곳이 로그인 관련 코드뿐이라 나중에 붙이면 될 것 같아요.
- 추정 시간 :
- 걸린 시간 :

[BE] refactor: readonly 제거

---

backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
backend/src/main/java/com/funeat/auth/presentation/AuthController.java
backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java

- close #187 
- 로그인 Swagger 문서 추가
- 로그인이 6번인데, 회원 정보 PR이 5번이라 나중에 머지가 필요합니다~
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.5

[BE] feat: 로그인 Swagger UI 추가

---

frontend/src/constants/index.ts

- close #208
정렬 필터링을 추가했습니다.
x
X
- 추정 시간 : 30분
- 걸린 시간 : 5분

[FE] feat: 정렬 필터링 추가

---

backend/src/main/java/com/funeat/member/application/MemberService.java
backend/src/main/java/com/funeat/member/dto/MemberProfileResponse.java
backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
backend/src/main/java/com/funeat/member/presentation/MemberController.java
backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
backend/src/test/java/com/funeat/member/application/MemberServiceTest.java

- close #205 
- 이전에 회원 정보를 수정하는 기능을 추가했고, 이번엔 회원 정보를 조회하는 기능을 추가했습니다.
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 0.5

[BE] 회원 정보를 조회하는 기능 추가

---

backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
backend/src/test/java/com/funeat/acceptance/common/LoginSteps.java
backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java

- close #218 
- POST -> GET
- 302 Found -> 200 OK
- Location 반환은 그대로 유지
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.05

[BE] fix: POST -> GET, 302 Found -> 200 OK로 변경

---

frontend/src/hooks/auth/useAuth.ts
frontend/src/mocks/handlers/loginHandlers.ts
frontend/src/pages/AuthPage.tsx

- close #219
- 세션 아이디 요청 메서드 POST -> GET으로 수정
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분

[FE] refactor: 세션 아이디 요청 메서드 POST -> GET으로 수정

---

frontend/src/pages/AuthPage.tsx

- close #228 
- 회원 정보 요청 주석 처리
x
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 회원 정보 요청 제거

---

frontend/src/components/Common/SortButton/SortButton.tsx
frontend/src/components/Common/Title/Title.tsx
frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx

- close #151
- 버튼 태그 내부에 div가 들어간 경우들을 a태그로 수정했습니다.
x
x
- 추정 시간 : 2시간
- 걸린 시간 : 10분

[FE] refactor: 버튼 내부에 div 태그 제거

---

frontend/src/pages/AuthPage.tsx

- close #230 
- 세션 아이디 요청에 credentials 옵션 추가
x
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 세션 아이디 요청에 credentials 옵션 추가

---

frontend/src/components/Product/PBProductItem/PBProductItem.tsx
frontend/src/components/Product/ProductItem/ProductItem.tsx

- close #232
- 추정 시간 :
- 걸린 시간 :

[FE] fix: svg alt 오류 수정

---

backend/src/main/java/com/funeat/common/WebConfig.java

- close #236 
- CORS 관련 설정 제거
x
x
- 추정 시간 : 5min
- 걸린 시간 : 5min

[BE] fix: CORS 설정 Nginx로 이관

---

frontend/src/pages/AuthPage.tsx

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 세션 아이디 로그 확인

---

backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
backend/src/main/java/com/funeat/common/WebConfig.java

- close #243 
- MemberHandlerInterceptor의 매핑 url 수정
- X
- X
- 추정 시간 :
- 걸린 시간 :

fix: MemberHandlerInterceptor의 매핑 url pattern 수정

---

backend/src/main/java/com/funeat/auth/util/MemberHandlerInterceptor.java
backend/src/main/java/com/funeat/common/WebConfig.java

- close #245 
- 추정 시간 :
- 걸린 시간 :

[BE] feat: 디버그용 log 추가

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #248 
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 리뷰 작성 헤더 삭제

---

backend/build.gradle

- close #250 
- 파일 업로드 라이브러리 추가
- x
- x
- 추정 시간 : 0.01
- 걸린 시간 : 0.01

[BE] chore: 파일 업로드 관련 의존성 추가

---

backend/build.gradle

- x
- x
- x
- x
- 추정 시간 : 0.01
- 걸린 시간 : 0.01

[BE] fix: 의존성 에러 수정

---

backend/build.gradle
backend/src/main/resources/application.yml

- x
- x
- x
- x
- 추정 시간 : 0.01
- 걸린 시간 : 0.01

[BE] chore: multipart 관련 yml 수정

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] fix: blob 추가

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
frontend/src/hooks/review/useReviewImageUploader.ts

- close #256 
이미지 링크 수정하였습니다.
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 이미지 링크 수정

---

frontend/src/apis/ApiClient.ts
frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
frontend/src/hooks/review/useReviewImageUploader.ts

- close #258
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 이미지 링크 전송 함수 작성

---

backend/build.gradle

- close #261 
- 파일 업로드 관련한 의존성 제거 후 잘 동작하는지 테스트
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] chore: 파일 업로드 관련 의존성 제거

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/hooks/review/useReviewFavorite.ts

- close #267
- 리뷰 좋아요 요청 수정
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 10분

[FE] feat: 리뷰 좋아요 요청 수정

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/types/review.ts

- close #269 
- 리뷰 좋아요 요청 본문 수정
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 리뷰 좋아요 요청 본문 수정

---

backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java

- close #237 
- 리뷰 정렬 페이징 dto에 리뷰가 언제 작성됐는지 작성 시간을 추가합니다.
- x
- x
- 추정 시간 : 0.000001
- 걸린 시간 : 0.0001

[BE] refactor: 리뷰 페이징 dto에 작성 시간을 추가

---

backend/src/main/java/com/funeat/auth/dto/SignUserDto.java
backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
backend/src/test/java/com/funeat/auth/presentation/AuthApiControllerTest.java
backend/src/test/java/com/funeat/member/application/MemberServiceTest.java

- close #240
- 기존 회원은 홈으로, 신규 회원은 마이페이지로 이동
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.2

[BE] fix: 기존 회원은 홈으로, 신규 회원은 마이페이지로 이동

---

backend/src/main/java/com/funeat/review/application/ReviewService.java

- close #275 
- 리뷰 좋아요 관련 분기 처리 수정
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: 리뷰 좋아요가 존재하거나 존재하지 않을 때 분기처리 수정

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/types/review.ts

- close #277 
- 리뷰 좋아요 요청 본문 수정
- 추정 시간 : 10분
- 걸린 시간 : 2분

[FE] feat: 리뷰 좋아요 요청 본문 수정

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #279
재구매 철자 수정과 이미지 경로를 수정했습니다.
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 재구매 철자 수정과 이미지 경로 수정

---

frontend/src/components/Review/ReviewList/ReviewList.tsx
frontend/src/components/Review/index.ts
frontend/src/contexts/ProductReviewContext.tsx
frontend/src/hooks/context/index.ts
frontend/src/hooks/context/useProductReviewContext.ts
frontend/src/hooks/product/index.ts
frontend/src/hooks/product/useInfiniteProductReviews.ts
frontend/src/hooks/product/useProductReview.ts
frontend/src/hooks/useGet.ts
frontend/src/mocks/handlers/productHandlers.ts
frontend/src/mocks/handlers/reviewHandlers.ts
frontend/src/pages/ProductDetailPage.tsx
frontend/src/router/index.tsx

- close #282 
- 리뷰 조회 회원, 비회원 처리
- 상품 리뷰 컨텍스트 생성
- useGet의 useEffect에서 에러를 던지고 있는데 현재 에러바운더리가 없어서 주석 처리했습니다.
- 추정 시간 : 2시간
- 걸린 시간 : 2시간

[FE] feat: 리뷰 조회 회원, 비회원 처리

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
frontend/src/contexts/ProductReviewContext.tsx
frontend/src/hooks/context/useProductReviewPageContext.ts
frontend/src/hooks/product/useInfiniteProductReviews.ts

- close #305 
타입 에러 수정과 페이지를 컨텍스트 분리하였습니다.
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 타입 에러 수정과 페이지 컨텍스트 분리

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #307 
폼 작성 후 리셋합니다.
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 폼 작성 후 리셋

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/pages/ProductDetailPage.tsx

- close #302 
- 리뷰 좋아요 시 리뷰 숫자 업데이트 구현
x
x
- 추정 시간 : 2시간
- 걸린 시간 : 1시간

[FE] feat: 리뷰 좋아요 시 리뷰 숫자 업데이트 구현

---

frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #309 
폼 작성 후 리셋 에러 수정하였습니다.
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 폼 작성 후 리셋 에러 수정

---

frontend/package.json
frontend/src/hooks/auth/index.ts
frontend/src/hooks/auth/useMember.ts
frontend/src/pages/AuthPage.tsx
frontend/src/pages/ProfilePage.tsx
frontend/yarn.lock

- close #313 
- 마이페이지에 접근하면 회원 정보 조회를 합니다. 에러가 나면 현재 저장된 회원 정보를 비우고 로그인 페이지로 리다이렉트
- 기타 credentials가 필요한 요청에서는 try/catch로 회원 정보 리셋 후 로그인 페이지로 리다이렉트 하면 될 것 같습니다.
x
- 추정 시간 : 1시간
- 걸린 시간 : 1시간

[FE] feat: 마이페이지 접근시 회원 정보 조회 요청 추가

---

frontend/src/components/Review/ReviewList/ReviewList.tsx
frontend/src/pages/ProfilePage.tsx

- close #318
- 상품 상세 로그인 필요 메시지에 로그인 링크 추가
x
x
- 추정 시간 : 10분
- 걸린 시간 : 20분

[FE] feat: 상품 상세 로그인 필요 메시지에 로그인 링크 추가

---

frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
frontend/src/hooks/review/useReviewImageUploader.ts

- close #321 
- 버튼 활성화 관련 에러 처리
- 이미지 용량 제한 처리
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 리뷰 작성 폼 에러 수정

---

backend/build.gradle
backend/src/main/resources/logback-spring.xml

- close #326 
- warn, error 발생 시 슬랙으로 알람기능
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 2

[BE] feat: warn, error 발생 시 슬랙으로 알람기능 추가

---

backend/build.gradle
backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml

- close #326 
- loggin yml 설정 추가입니다.
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] feat: warn, error 발생 시 슬랙으로 알람기능 yml 설정추가

---

frontend/package.json
frontend/webpack.common.js
frontend/yarn.lock

- close #361 
- 이미지 압축 패키지 설치 및 웹팩 설정 수정
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 이미지 압축 패키지 설치 및 웹팩 설정 수정

---

frontend/src/components/Common/ErrorBoundary/ErrorBoundary.tsx
frontend/src/components/Common/ErrorComponent/ErrorComponent.stories.tsx
frontend/src/components/Common/ErrorComponent/ErrorComponent.tsx
frontend/src/components/Common/Loading/Loading.stories.tsx
frontend/src/components/Common/Loading/Loading.tsx
frontend/src/pages/NotFoundPage.tsx
frontend/src/router/index.tsx

- close #358 
- NotFound 페이지 추가
- 에러바운더리 컴포넌트 추가
- 에러컴포넌트 추가
- 현재 에러바운더리에서는 fallback 컴포넌트에 message를 전달해주도록 되어있는데 이 구조는 나중에 고도화 하면서 수정하면 좋을 것 같습니다.
x
- 추정 시간 : 1~2
- 걸린 시간 : 1

[FE] feat: 에러, 로딩 UI 추가 

---

backend/src/main/resources/application.yml

- close #374 
- application.yml profile 환경변수 적용
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: application.yml profile 환경변수 설정

---

frontend/src/components/Common/TagList/TagList.tsx

- close #388 
태그 저장 오류를 해결합니다.
x
x

[FE] fix: 태그 저장 오류 해결

---

frontend/src/components/Common/SectionTitle/SectionTitle.stories.tsx
frontend/src/components/Common/SectionTitle/SectionTitleTitle.tsx
frontend/src/components/Common/index.ts
frontend/src/components/Product/index.ts
frontend/src/pages/ProductDetailPage.tsx

- close #390 
productTitle을 sectionTitle로 이름을 변경하였습니다.
x
x
- 추정 시간 : 30분
- 걸린 시간 : 5분

[FE] refactor: productTitle 이름 변경

---

backend/build.gradle
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml

- close #378 
- 프로메테우스 + 그라파나로 모니터링 기능을 사용합니다.
- 나중에 인프라 서버 터질 때 노션에 내용 자세하게 적어두었어요
- x
- 추정 시간 : 12
- 걸린 시간 : 12

[BE] feat: 모니터링 대시보드 추가

---

backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml

- close #397
- yaml 에러 발생
- x
- x
- 추정 시간 : 0.000000001
- 걸린 시간 : 0.0000000000000001

[BE] fix: yml 에러 수정

---

.github/release-drafter.yml
.github/workflows/release.yml

- close #410 
- 릴리즈 노트 워크플로우 작성
x
x
- 추정 시간 : 0.2시간

[ALL] chore: 릴리즈 노트 워크플로우 작성

---

frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
frontend/src/mocks/data/productRankingList.json
frontend/src/types/ranking.ts

- close #320 
- close #335 
- 상품 랭킹 클릭 시 해당 상품으로 라우팅 기능 추가
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분

[FE] feat: 상품 랭킹 클릭 시 해당 상품으로 라우팅 기능 추가

---

backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java

- close #436
- 신규 회원의 경우 `/profile`로 이동하고 있는데, `/members`로 수정해야 합니다
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] refactor: 신규 회원 리다이렉트 주소 변경

---

frontend/src/components/Product/ProductList/ProductList.tsx
frontend/src/pages/ProductListPage.tsx

- close #438
- 상품 리스트 페이지에서 정렬 옵션 props로 전달
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 상품 리스트 정렬 에러 수정

---

backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
backend/src/main/java/com/funeat/member/dto/MemberRecipeProductDto.java
backend/src/main/java/com/funeat/recipe/application/RecipeService.java
backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java

- close #458 
- api 명세 수정으로 dto 수정입니다.
- x
- x
- 추정 시간 : 0.2
- 걸린 시간 : 0.3

[BE] refactor: 마이페이지 꿀조합 조회 api 명세 조회 수정

---

backend/src/main/java/com/funeat/common/WebConfig.java
backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
backend/src/main/java/com/funeat/member/persistence/RecipeFavoriteRepository.java
backend/src/main/java/com/funeat/recipe/application/RecipeService.java
backend/src/main/java/com/funeat/recipe/domain/Recipe.java
backend/src/main/java/com/funeat/recipe/dto/RecipeFavoriteRequest.java
backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
backend/src/test/java/com/funeat/common/RepositoryTest.java
backend/src/test/java/com/funeat/fixture/ImageFixture.java
backend/src/test/java/com/funeat/fixture/RecipeFixture.java
backend/src/test/java/com/funeat/member/domain/favorite/RecipeFavoriteTest.java
backend/src/test/java/com/funeat/member/persistence/RecipeFavoriteRepositoryTest.java
backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java

- close #414
꿀조합 좋아요 기능 구현
- `RecipeHandlerInterceptor` 경로
- X
- 추정 시간 : 2
- 걸린 시간 : 3

[BE] feat: 꿀조합 좋아요 기능 구현

---

frontend/.nvmrc
frontend/src/components/Product/ProductDetailItem/ProductDetailItem.stories.tsx
frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
frontend/src/mocks/data/productDetail.json
frontend/src/mocks/data/productDetails.json
frontend/src/pages/ProductDetailPage.tsx
frontend/src/types/product.ts

- close #473 
- 상품 상세에서 전체 리뷰 수 추가
- 상품 상세 타입 수정
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 30분

[FE] feat: 상품 상세에서 전체 리뷰 수 추가

---

frontend/src/hooks/queries/recipe/useRecipeRegisterFormMutation.ts

- close #483 
- 백엔드에서 앞에 `/api`를 붙여주기 때문에 제거
x
x
- 추정 시간 : 5분
- 걸린 시간 : 5분

[FE] refactor: 꿀조합 작성 후 리다이렉트 경로 수정

---

backend/src/main/java/com/funeat/auth/application/AuthService.java
backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
backend/src/main/java/com/funeat/auth/presentation/AuthController.java
backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
backend/src/main/java/com/funeat/auth/util/PlatformUserProvider.java
backend/src/main/java/com/funeat/common/WebConfig.java
backend/src/main/java/com/funeat/member/application/MemberService.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-prod.yml
backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
backend/src/test/java/com/funeat/acceptance/common/TestPlatformUserProvider.java
backend/src/test/java/com/funeat/auth/application/AuthServiceTest.java
backend/src/test/java/com/funeat/member/application/MemberServiceTest.java

- close #465 
- 로그아웃 기능
- yaml에 카카오 admin-key 추가했습니다.
- 노션에 admin-key 추가
- 젠킨스에 dev는 추가했는데, **prod는 main 배포할 때 추가해야합니다.** 
- x
- 추정 시간 : 1
- 걸린 시간 : 2

[BE] refactor: 카카오 로그아웃 기능 수정

---

frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
frontend/src/hooks/common/useFormData.ts
frontend/src/pages/RecipeDetailPage.tsx

- close #482 
- 이미지 경로 추가
- 이미지 이름 blob으로 오는 오류 해결
x
x

fix: 이미지 오류 수정

---

frontend/src/hooks/common/useFormData.ts
frontend/src/hooks/common/useImageUploader.ts

- close #491
- 사진 압축 option에 fileType 추가
x
x
- 추정 시간 : 5분
- 걸린 시간 : 1분

[FE] feat: options에 fileType: image/png 추가

---

backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java

- close #493  
- x
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] fix: request -> memberRequest

---

frontend/src/apis/index.ts
frontend/src/components/Members/MembersInfo/MembersInfo.tsx
frontend/src/hooks/queries/members/index.ts
frontend/src/hooks/queries/members/useLogoutMutation.ts
frontend/src/mocks/browser.ts
frontend/src/mocks/handlers/index.ts
frontend/src/mocks/handlers/logoutHandlers.ts

- close #469 
로그아웃 기능을 구현하였습니다.
login의 경우 authPage에 함수가 그대로 구현되어 있더라구요.
logout도 일단 사용처에서 함수 그대로 구현하였는데, 따로 훅 파일을 팔까요?
x
- 추정 시간 : 3시간
- 걸린 시간 : 2시간

[FE] feat: 로그아웃 기능 구현

---

frontend/src/hooks/queries/members/useMemberModifyMutation.ts

- close #496
invalidateQueries 추가 했습니다.
이렇게 작성하는거 맞나요??
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 5분

[FE] feat: invalidateQueries 추가

---

frontend/src/hooks/queries/members/useLogoutMutation.ts

- close #501
Member 새로고침과 경로 수정
x
x
- 추정 시간 : 10분
- 걸린 시간 : 5분

[FE] refactor: Member 새로고침과 경로 수정

---

frontend/src/components/Layout/AuthLayout.tsx
frontend/src/components/Members/MembersInfo/MembersInfo.tsx
frontend/src/hooks/queries/members/useMemberQuery.ts
frontend/src/hooks/queries/useSuspendedQuery.ts
frontend/src/mocks/handlers/logoutHandlers.ts
frontend/src/mocks/handlers/memberHandlers.ts
frontend/src/pages/MemberModifyPage.tsx

- close #505 
- useSuspendedQuery에서 에러를 컴포넌트 내에서 다룰 수 있게 반환 타입을 추가했습니다
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 로그아웃 멤버 초기화 수정

---

backend/src/main/java/com/funeat/product/domain/Product.java
backend/src/main/java/com/funeat/review/application/ReviewService.java
backend/src/main/java/com/funeat/review/domain/Review.java
backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
backend/src/test/java/com/funeat/acceptance/common/CommonSteps.java
backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
backend/src/test/java/com/funeat/fixture/ReviewFixture.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java

- close #476
- 이미지가 존재하는 리뷰중에 가장 많은 좋아요를 받은 리뷰 이미지로 상품 이미지 변경 기능 추가
- x
- git pull --rebase로 하면 예전 커밋 버전으로 돌아가서 merge commit 함
- 추정 시간 : 2
- 걸린 시간 : 4 (테스트 코드 작성하는데 오래 걸림)

[BE] feat: 이미지가 존재하는 리뷰중에 가장 많은 좋아요를 받은 리뷰 이미지로 상품 이미지 변경 기능 추가

---

frontend/src/hooks/queries/members/useLogoutMutation.ts

- close #515 
x
- 키 배열에 'member' 요소가 있는 쿼리 모두 삭제
- 추정 시간 :
- 걸린 시간 :

[FE] refactor: invalidateQueries를 removeQueries로 수정

---

frontend/src/components/Recipe/RecipeUsedProducts/RecipeUsedProducts.tsx

- close #506 
- 꿀조합 사용된 상품명 길이가 길 때 디자인 대응 
x
x
- 추정 시간 : 10분
- 걸린 시간 : 20분

[FE] feat: 꿀조합 사용된 상품명 길이가 길 때 디자인 대응

---

frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx

[FE] fix: 라우팅 에러 수정

---

backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java

- close #521 
- `RankingRecipeDto`에 title 추가
- X
- X
- 추정 시간 : 10min
- 걸린 시간 : 5min

[BE] refactor: 꿀조합 랭킹 Response 변경

---

frontend/src/components/Common/Carousel/Carousel.tsx
frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx

- close #511
- 작성한 리뷰/꿀조합 없을 때 예외 처리 
- 개행처리
- 따옴표 제거
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 20분

[FE] feat: 마이페이지 - 리뷰/꿀조합 없을 때 처리

---

frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx

- close #525
- 꿀조합 랭킹 컴포넌트 너비 수정
- 꿀조합 랭킹 없을 때 예외처리
x
x

[FE] refactor: 꿀조합 랭킹 컴포넌트 너비 수정

---

frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
frontend/src/components/Review/ReviewItem/ReviewItem.tsx
frontend/src/mocks/data/productDetail.json
frontend/src/mocks/data/productDetails.json
frontend/src/pages/LoginPage.tsx
frontend/src/pages/ProductDetailPage.tsx

- close #541 
- 상품 설명, 리뷰 텍스트 개행 문자 스타일 처리
- 기타 pre-line -> pre-wrap으로 수정 (pre-line은 개행이 여러개 들어가도 하나로 처리함)
- break-word는 한중일 문자에 적용되지 않음, 그래서 삭제
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분

[FE] refactor: 개행 문자 스타일 처리

---

backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
backend/src/main/java/com/funeat/review/application/ReviewService.java
backend/src/main/java/com/funeat/tag/domain/TagType.java
backend/src/test/java/com/funeat/fixture/TagFixture.java
backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
backend/src/test/java/com/funeat/product/domain/favorite/ReviewFavoriteTest.java

- close #385
- createReviewFavoriteByMemberAndReview → create
- [TagType] : PRICE → QUANTITY
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] refactor: 정팩메 수정, 태그 종류 변경

---

frontend/src/components/Review/ReviewTagItem/ReviewTagItem.tsx
frontend/src/constants/index.ts
frontend/src/mocks/data/productDetail.json
frontend/src/mocks/data/productDetails.json
frontend/src/mocks/data/reviewTagList.json
frontend/src/types/common.ts
frontend/src/utils/convertTagColor.ts

- close #523
- https://github.com/woowacourse-teams/2023-fun-eat/pull/520 으로 인해 타입 이름 변경
x
x
- 추정 시간 :
- 걸린 시간 : 5분

[FE] refactor: tag variant 타입 PRICE->QUANTITY로 네이밍 변경

---

frontend/src/types/review.ts

- close #550
- 수정 안 된 import 문 수정
x
x
- 추정 시간 : 1분
- 걸린 시간 : 1분

[FE] fix: 수정 안 된 import문 수정

---

frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx

- close #528
- image 위치 가운데로 수정합니다.
x
x
- 추정 시간 : 5분
- 걸린 시간 : 5분

[FE] refactor: image 위치 가운데로 수정

---

frontend/src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
frontend/src/hooks/queries/product/useInfiniteProductsQuery.ts
frontend/src/hooks/queries/product/useProductDetailQuery.ts
frontend/src/hooks/queries/review/useReviewFavoriteMutation.ts
frontend/src/hooks/queries/review/useReviewRegisterFormMutation.ts

- close #539
product detail invalidateQueries 추가
invalidateQueries를 잘 작성했는지 확인해주세용
x
- 추정 시간 : 30분
- 걸린 시간 : 5분

[FE] refactor: product detail invalidateQueries 추가

---

frontend/src/hooks/queries/members/useInfiniteMemberReviewQuery.ts
frontend/src/hooks/queries/product/useInfiniteProductRecipesQuery.ts
frontend/src/hooks/queries/product/useInfiniteProductReviewsQuery.ts
frontend/src/hooks/queries/product/useProductDetailQuery.ts

- close #553 
query key 순서 변경합니다.
x
x

[FE] fix: query key 순서 변경

---

frontend/src/components/Recipe/RecipeUsedProducts/SearchedProductList.tsx

- close #555
- 오타 수정
- 사용된 상품 자동완성 높이 수정
x
x
- 추정 시간 :
- 걸린 시간 : 5분

[FE] style: 오타 수정 및 사용된 상품 자동완성 높이 수정

---

frontend/public/index.html

- close #560 
- 구글 애널리틱스 스크립트 추가
- 각종 이벤트를 분석하는 훅도 있어보이는데 일단 스크립트만 추가했습니다.
- dev, prod 구분하지 않았습니다.
- 개강하면 추가적으로 진행해보아요.!
- 젠킨스에 환경변수 추가했습니다
- 추정 시간 : 30분
- 걸린 시간 : 10분

[FE] feat: 구글 애널리틱스 스크립트 추가

---

frontend/src/hooks/common/useImageUploader.ts

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 이미지 업로드 에러 콘솔 추가

---

backend/build.gradle
backend/src/main/java/com/funeat/common/OpenApiConfig.java
backend/src/main/java/com/funeat/common/controller/PreSingedApiController.java
backend/src/main/java/com/funeat/common/controller/PreSingedController.java
backend/src/main/java/com/funeat/common/dto/S3UrlRequest.java
backend/src/main/java/com/funeat/common/dto/S3UrlResponse.java
backend/src/main/java/com/funeat/common/s3/AwsConfig.java
backend/src/main/java/com/funeat/common/s3/S3UploadUrlGenerator.java
backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/test/resources/application.yml

- close #588 
- 이미지를 프론트에서 업로드 하기 위해서 pre-signed-url 을 내려주는 api 를 구현하였습니다.
- yml 을 보시면
- bucket = s3 이름
- folder = s3 내 저희 폴더 내 dev or prod
- expiration.time = pre-singed-url 에 접근할 수 있는 유효 시간입니다.
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 1

[BE] feat: S3 pre-singed-url 반환 기능 구현

---

backend/src/main/java/com/funeat/common/s3/S3Uploader.java

- close #600 
- x
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.5

[BE] hotfix: s3 path 를 file full path 로 수정

---

backend/src/main/java/com/funeat/common/s3/S3Uploader.java

- close #600 
- x
- x
- x
- 추정 시간 : 무한
- 걸린 시간 : 1

[BE] hotfix: s3 권한을 얻을 때 읽기 권한 추가 삭제

---

backend/src/main/java/com/funeat/common/s3/S3Uploader.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml
backend/src/test/resources/application.yml

- close #600 
- x
- x
- x
- 추정 시간 : 무한
- 걸린 시간 : 1

[BE] hotfix: cloudfront path 로 이미지 url 변경

---

frontend/src/components/Review/ReviewItem/ReviewItem.tsx

- close #605 
- 이미지 없을 때 null -> '' 으로 수정
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 리뷰 이미지 예외처리 수정

---

backend/src/main/java/com/funeat/member/dto/MemberReviewDto.java
backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java

- close #613 
- 리뷰 랭킹 조회api의 반환값에 상품의 categoryType 추가
- 마이페이지 리뷰 조회api의 반환값에 상품의 categoryType 추가
- X
- X
- 추정 시간 : 0.5
- 걸린 시간 : 0.5

[BE] feat: 리뷰 랭킹 조회api와 마이페이지 리뷰 조회api에서 반환값에 상품의 categoryType 추가

---

frontend/src/constants/index.ts
frontend/src/hooks/common/useRouteChangeTracker.ts
frontend/src/index.tsx

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] refactor: 프로덕션 환경에서만 ga 동작하게 수정

---

frontend/src/components/Product/ProductTitle/ProductTitle.stories.tsx

- close #629
- content로 변수명 수정
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 변수명 수정

---

frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx

- close #645
- 추정 시간 :
- 걸린 시간 :

[FE] refactor: 리뷰 태그 리스트 스타일 수정

---

frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx

- close #648
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 리뷰, 꿀조합 전송 에러 수정

---

frontend/src/components/Product/ProductTitle/ProductTitle.tsx
frontend/src/hooks/common/useIntersectionObserver.ts
frontend/src/pages/RecipePage.tsx

- close #658
- 현재 갤럭시 기종에서 무한스크롤이 되지 않아 height를 변경했습니다.

[FE] fix: 갤럭시에서 무한스크롤 안되는 문제 해결

---

frontend/src/components/Product/ProductList/ProductList.tsx
frontend/src/components/Recipe/RecipeList/RecipeList.tsx

[FE] fix: 옵저버 div에 높이 설정

---

frontend/src/hooks/queries/recipe/useRecipeFavoriteMutation.ts
frontend/src/hooks/queries/review/useReviewFavoriteMutation.ts

- close #673
- 좋아요 성공시 onSuccess에 해당 쿼리 무효화했습니다..!
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 좋아요 요청 시 상품 리뷰와 꿀조합 상세 쿼리 무효화

---

frontend/package.json
frontend/yarn.lock

- close #689
webpack-bundle-analyzer 설치해 오류를 해결했습니다.

[FE] fix: webpack-bundle-analyzer 설치

---

frontend/package.json
frontend/webpack.common.js
frontend/yarn.lock

- close #691
webpack-bundle-analyzer 삭제하였습니다.

[FE] fix: webpack-bundle-analyzer 삭제

---

backend/src/main/resources/application.yml

- close #694 
톰캣의 스레드풀 설정 추가
```
server:
tomcat:
threads:
max: { MAX_THREADS }
min-spare: { MIN_SPARE }
max-connections: { MAX_CONNECTIONS }
accept-count: { ACCEPT_COUNT }
connection-timeout: { CONNECTION_TIMEOUT }
```
- X
- 성능테스트를 통해 적절한 설정값을 찾아봅시다
- 추정 시간 : 0.1
- 걸린 시간 : 0.1

[BE] feat: application.yml에 톰캣 스레드 설정 항목 추가

---

frontend/public/index.html
frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
frontend/src/mocks/data/productRankingList.json

- close #698
- close #699
폰트를 가변 다이나믹으로 변경하였습니다.
상품 랭킹을 말줄임표로 바꾸었습니다.
x
x
- 추정 시간 : 40분
- 걸린 시간 : 15분

[FE] refactor: 폰트 가변 다이나믹으로 변경과 상품 랭킹 말줄임표

---

frontend/package.json
frontend/yarn.lock

- close #702
디자인 시스템 버전을 올렸습니다.
x
x
- 추정 시간 : 1분
- 걸린 시간 : 1분

[FE] chore: 디자인 시스템 버전 업

---

frontend/src/components/Product/ProductItem/ProductItem.tsx
frontend/src/components/Product/ProductList/ProductList.tsx
frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx

- close #696
- position: relative 추가
- 꿀조합 페이지 스켈레톤 너비 수정
x
x
- 추정 시간 :1분
- 걸린 시간 : 5분

[FE] fix: 상품 목록 페이지에서 스크롤이 2개 생기는 버그 해결

---

frontend/src/components/Product/ProductItem/ProductItem.tsx
frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
frontend/src/components/Review/ReviewItem/ReviewItem.tsx

- close #704 
- 상품, 꿀조합, 리뷰 아이템 메모이제이션
- 추정 시간 :
- 걸린 시간 :

[FE] refactor: 상품, 꿀조합, 리뷰 아이템 메모이제이션

---

frontend/src/pages/HomePage.tsx

- close #708 
- 인스타그램 이동 링크 변경
x
x
- 추정 시간 : 1분
- 걸린 시간 : 1분

[FE] feat: 이벤트 링크 변경

---

frontend/src/pages/HomePage.tsx

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] feat: 배너 링크 삭제

---

frontend/package.json
frontend/src/components/Common/TagList/TagList.tsx
frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
frontend/src/components/Review/BestReviewItem/BestReviewItem.stories.tsx
frontend/src/components/Review/BestReviewItem/BestReviewItem.tsx
frontend/src/components/Review/index.ts
frontend/src/hooks/queries/rank/index.ts
frontend/src/hooks/queries/rank/useBestReviewQuery.ts
frontend/src/mocks/handlers/rankingHandlers.ts
frontend/src/pages/ProductDetailPage.tsx
frontend/yarn.lock

- close #720
- 베스트 리뷰 추가 (리뷰 없으면 노출 x)
x
x
- 추정 시간 : 
- 걸린 시간 : 1.5

[FE] 로그인 안했을 때도 리뷰를 1개 확인할 수 있는 기능 구현

---

backend/src/main/java/com/funeat/review/application/ReviewService.java
backend/src/main/java/com/funeat/review/dto/MostFavoriteReviewResponse.java
backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
backend/src/main/java/com/funeat/review/presentation/ReviewController.java
backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java

- close #713 
- 좋아요를 가장 많이 받은 리뷰를 응답하는 API
- 1) 데이터가 존재할 때 -> 정상 반환 (200)
- 2) 데이터가 존재하지 않을 때 -> 빈 응답을 반환 (200)
- 데이터가 존재하지 않을 때 200이 맞을까요?
데이터가 존재하지 않을 때 204 No Content 사용
- x
- 추정 시간 : 2
- 걸린 시간 : 2

[BE] 특정 상품에서 좋아요를 가장 많이 받은 리뷰를 응답하는 API 연결

---

frontend/src/components/Common/Carousel/Carousel.tsx

- close #733 
캐러셀 마지막 index를 수정하였습니다.
x
x
- 추정 시간 : 5분
- 걸린 시간 : 1분

[FE] refactor: 캐러셀 Index 수정

---

frontend/src/components/Review/BestReviewItem/BestReviewItem.tsx
frontend/src/hooks/queries/rank/useBestReviewQuery.ts

- close #741 
- 204 일때 응답 데이터가 없어서 .json() 에러 발생해서 처리했어요~
없습니다.!
없습니다.!
- 추정 시간 : 10분
- 걸린 시간 : 10분

[FE] fix: 베스트리뷰 요청 204 처리

---

backend/src/main/java/com/funeat/auth/application/AuthService.java

- close #748 
- 삭제하는 쿠키 이름을 `JSESSIONID`에서 `SESSION`으로 변경합니다.
- x
- 테스트 환경을 MySQL로 바꿀 경우, Steps에 있는 `JSESSIONID`도 모두 `SESSION`으로 변경되어야 합니다.
- 추정 시간 : 0.0001
- 걸린 시간 : 0.0000000000000000000001

[BE] fix: 로그아웃시 쿠키가 삭제되도록 수정

---

frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts

- close #767
- 꿀조합 댓글 조회 credentials 추가
x
x
- 추정 시간 : 5분
- 걸린 시간 : 5분

[FE] feat: 꿀조합 댓글 조회에 credentials 추가

---

frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts

- close #769
- totalElements가 없는 경우 query string에서 제외
x
x
- 추정 시간 : 5분
- 걸린 시간 : 5분

[FE] fix: totalElements가 없는 경우 query string에서 제외

---

frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts

- close #773
- 아예 첫 조회때는 lastId도 보내지 않는 것이라고 하네요..
x
x
- 추정 시간 :
- 걸린 시간 :

[FE] feat: totalElements가 null일 때 아예 쿼리를 보내지 않도록 수정

---

frontend/src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx

- close #782
- 추정 시간 :
- 걸린 시간 :

[FE] fix: storybook에서 바뀐 변수명 수정

---

frontend/src/components/Recipe/RecipeFavorite/RecipeFavorite.tsx
frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx

- close #798 
꿀조합 등록 토스트를 '좋아요'에 해서 위치를 변경하였습니다.
x
x

fix: 꿀조합 등록 토스트 위치 이동

---

frontend/src/components/Recipe/CommentList/CommentList.tsx

- close #799
- totalElements와 comments를 destructing 하는 방법을 수정했습니다
x
x
- 추정 시간 : 5분
- 걸린 시간 : 5분

[FE] fix: 꿀조합 무한스크롤 되지 않는 버그 해결

---

backend/src/main/java/com/funeat/review/dto/SortingReviewDtoWithoutTag.java

- close #807
- 좋아요를 취소했으면 좋아요가 취소된 것으로 변경
- x
- x
- 추정 시간 : 0.00000001
- 걸린 시간 : 0.00000000001

[BE] fix: 좋아요 취소도 좋아요를 누르지 않은 것으로 설정

---

backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java

- close #820 
- 리뷰 및 꿀조합 랭킹 dto 수정
- `RankingReviewDto` 및 `RankingRecipeDto`에 `createdAt` 추가
X
X
- 추정 시간 : 10min
- 걸린 시간 : 10min

[BE] refactor: 리뷰 및 꿀조합 랭킹 Response 수정

---

frontend/src/components/Rank/RecipeRankingItem/RecipeRankingItem.tsx
frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.stories.tsx
frontend/src/components/Rank/ReviewRankingItem/ReviewRankingItem.tsx
frontend/src/mocks/data/recipeRankingList.json
frontend/src/mocks/data/reviewRankingList.json
frontend/src/types/ranking.ts

- close #824 
- 꿀조합, 리뷰 랭킹 상대 시간 추가
- 추정 시간 : 30분
- 걸린 시간 : 20분

[FE] feat: 랭킹 상대 시간 추가

---

README.md

- close #825 
다크모드를 위해 로고 이미지를 수정하였습니다.
x
x

[ALL] docs: 로고 이미지 수정

---

frontend/src/components/Product/ProductItem/ProductItem.tsx

- close #이슈번호
- 추정 시간 :
- 걸린 시간 :

[FE] fix: 상품 아이템 null 처리 제거
