woowacourse-teams/2023-fun-eat

- backend/src/main/java/com/funeat/member/domain/Member.java
- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/domain/Review.java
- backend/src/main/java/com/funeat/review/domain/ReviewTag.java
- backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
- backend/src/main/java/com/funeat/review/presentation/ReviewController.java
- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewsPageDto.java
- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewsResponse.java
- backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #22 
- 특정 상품에 대한 리뷰 목록을 좋아요 기준 내림차순으로 페이징하여 반환하는 API 제공
- sort가 `RequestParam`의 `sort`에 매핑되는 것뿐만 아니라 `Pageable`의 `sort`에도 매핑되어 다른 네이밍이 필요합니다
- 리뷰 엔티티에 좋아요 개수 필드를 추가했습니다
- 페이징을 할 때 시작 페이지가 0입니다
- 다음주엔 도메인 생성자, getter, 리포지토리를 전부 추가해두고 나머지 개발을 시작하는게 좋아보입니다
- 어제 코드가 다 날아가서 ㅠㅠ 다시 시작하기 전에 우가랑 겹치는 코드가 많은 것 같아 우가 코드 베이스로 만들었습니다
커밋 메시지들은 다음주에 수정할게요!
> [BE] feat: 특정 상품의 리뷰 목록 조회 기능 추가 

- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
- backend/src/main/java/com/funeat/review/presentation/ReviewController.java
- backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewDto.java
- backend/src/main/java/com/funeat/review/presentation/dto/RankingReviewsResponse.java
- backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
- close #41 
- 좋아요를 기준으로 내림차순으로 상위 3개의 리뷰 정보를 반환하는 기능을 추가했습니다.
- 이것도 favoriteCount를 가지고 동작합니다
> [BE] feat: 좋아요 수를 기준으로 리뷰 랭킹 조회 기능 추가

- frontend/src/components/Product/PBProductItem/PBProductItem.stories.tsx
- frontend/src/components/Product/PBProductItem/PBProductItem.tsx
- frontend/src/components/Product/PBProductList/PBProductList.stories.tsx
- frontend/src/components/Product/PBProductList/PBProductList.tsx
- frontend/src/mocks/data/pbProducts.json
- frontend/src/types/product.ts
- close #72
- 편의점 PB 상품 아이템 컴포넌트 추가하였습니다.
웁스...진짜 길게 적었는데 잘못 눌러서 꺼졌어요...ㅠ 
일단 기억나는대로 다시 적어보겠습니다.
먼저, 아래 코드와 같이 작성했는데요.
```js
<Text
as="span"
size="sm"
weight="bold"
color={theme.textColors.info}
css={`
margin-left: 5px;
`}
>
```
css만 적으면 앞에 size나 color가 적용이 안됩니다.
처음에는 color만 적용 안되더니 나중엔 적용되고, 이젠 size가 작동이 안되고 후...
왜 이런지 아는분 계신가요??
그냥 css 부분 다 지워버리고 styled로 처리해버렸습니다.
그래서 약간 지저분해졌는데 불필요한 부분 있으면 말씀해주세요!
별점과 가격을 포함하고 있는 div의 이름을 추천해주세요...
도~~저히 생각이 안나서 `PBProductDetailInfoWrapper`로 했는데 더 좋은 이름이 있다면 추천바랍니당
컴포넌트 사이즈는 제가 임의로 작성했습니다.
레이아웃 나오고 페이지에 붙였을 때 아마 다시 사이즈 수정해야할 거 같아요!
일단 제목은 두줄에서 한줄로 수정했습니다.
이 컴포넌트가 한 아이템이 차지할 수 있는 width가 좁은데 두줄로 하니까 상품명이 애매하게 끊기더라구요.
그래서 한줄로 바꾸고 말줄임표 처리하였습니다.
피그마대로 만들었는데 디자인도 조금 수정해야할 거 같습니다.
혹시 좋은 디자인 아이디어가 있다면 적극 반영하겠습니다~~
x
- PBProductItem
- PBProductList
- 추정 시간 : …
> [FE] feat: 편의점 PB 상품 아이템 컴포넌트 추가

- frontend/src/components/Common/Title/Title.tsx
- frontend/src/components/Common/index.ts
- frontend/src/constants/path.ts
- frontend/src/pages/ProductList.tsx
- frontend/src/pages/ProductListPage.tsx
- frontend/src/router/index.tsx
- close #64 
- productList의 path를 변경하였습니다.
- Title의 크기를 변경하였습니다.
- 상품 리스트 페이지를 마크업 하였습니다.
마크업에만 중점을 맞춰서 따로 정렬이나 카테고리 기능은 구현하지 않았습니다.
바텀시트가 전체 넓이의 100%로 적용이 됩니다.
아래가 완성된 페이지입니다.
높은 가격순 버튼 아래에 상품 리스트가 있습니다.
혹시 버튼과 상품 리스트 간의 간격을 더 좁히고 싶으면 따로 말씀해주세요.
지금은 따로 spacing 같은 간격은 없고 li 태그 자체 padding만 존재합니다.
Title 컴포넌트에 css를 작성했습니다.
근데 지금보니 적용이 안되네요...ㅠ
그래서 어쩔 수 없이 Title의 as를 h2로 바꾸었습니다.
(css는 font-size였는데 삭제함...)
- 추정 시간 : 1시간
- 걸린 시간 : 1시간
> [FE] feat: 상품 리스트 페이지 마크업

- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #103 
- 특정 상품에서 평점 기준 오름차순으로 리뷰 목록을 조회하는 인수 테스트, 서비스 테스트 추가
- 특정 상품에서 평점 기준 내림차순으로 리뷰 목록을 조회하는 인수 테스트, 서비스 테스트 추가
- 테스트를 작성하다보니 만약 정렬하는 값이 같은 이후를 생각해보지 못한 것 같아요. 그래서 담주에 이야기 해보면 좋을 것 같습니다.
- 참고: #116 
- 나머지 기능은 이미 구현되어 있어서 테스트만 추가했습니다.
- 추정 시간 : 1
- 걸린 시간 : 0.5
> [BE] test: 특정 상품에서 평점순으로 리뷰 목록을 조회하는 테스트 추가

- frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.stories.tsx
- frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
- close #106 
- 리뷰 사진을 1장까지 업로드 할 수 있습니다.
- 사진을 업로드하고 사진을 삭제할 수 있습니다.
- 이미지 미리보기 기능도 넣었는데 어떤가요? 그리고 이미지 미리보기의 경우 사이즈를 고정해야할 것 같은데 몇으로 하면 좋을까요?
- 사진을 어떻게 보낼지에 따라 저장하는 state의 타입이 달라질 것 같네요
- 추정 시간 : 2시간
- 걸린 시간 : 2시간
업로드 전
업로드 후
> [FE] feat: 리뷰 사진 업로드 컴포넌트 추가

- frontend/package.json
- frontend/src/components/Review/ReviewTextarea/ReviewTextarea.stories.tsx
- frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
- frontend/yarn.lock
- close #109 
- 리뷰 작성 컴포넌트 구현
x
- 텍스트 value는 추후 폼에 추가하면서 바뀔 듯 합니다.
- Textarea의 크기는 컨테이너에 맞춰 잡힙니다.
- 추정 시간 : 1시간
> [FE] feat: 리뷰 작성 컴포넌트 구현

- .github/workflows/test.yml
- x
- x
- x
- x
- 추정 시간 : x
- 걸린 시간 : x
> [BE] test: test github actions workflow script 작성

- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/product/dto/ProductInCategoryDto.java
- backend/src/main/java/com/funeat/product/dto/ProductsInCategoryPageDto.java
- backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
- close #134 
카테고리별 상품 목록 조회 조건에 `평점순`과 `리뷰개수순` 추가
- 오전에 논의했던 대로 `@formula`사용 대신 조회에 사용되는 repository 메서드 분리 
- findAllByCategory : 평점순/가격순
- findAllByCategoryOrderByReviewCountDesc : 리뷰개수순
- findAll~의 반환값을 `Page<Product>`에서 `Page<ProductInCategoryDto>`로 수정
- 기타 개선사항
- 기존 count 쿼리 10번 -> 현재 1번
- 페이징의 totalCount를 위한 count 쿼리에서 join 제외
- ProductAcceptanceTest에서 테스트의 중심이 아닌 Review 데이터 세팅할 때
- reviewRepository.save(new Review~);
- restAssured로 review 작성 api 요청
-  X
- 추정 시간 : 2h
- 걸린 시간 : 6h
> [BE] feat : 카테고리별 상품 목록 조회시 정렬 조건 추가 (평점순 / 리뷰개수순)

- backend/src/test/java/com/funeat/member/persistence/ReviewFavoriteRepositoryTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #154 
- 기존: Service Test는 `@Transactional`만 사용하여 테스트 격리를 함
- 수정: Service Test는 `DataCleaner`를 추가하여 통일된 테스트 격리를 함
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 :
> [BE] fix: Service Test에 Data Cleaner 적용

- backend/src/main/java/com/funeat/product/dto/ProductResponse.java
- backend/src/main/java/com/funeat/tag/application/TagService.java
- backend/src/main/java/com/funeat/tag/domain/Tag.java
- backend/src/main/java/com/funeat/tag/domain/TagType.java
- backend/src/main/java/com/funeat/tag/dto/TagDto.java
- backend/src/main/java/com/funeat/tag/dto/TagsResponse.java
- backend/src/main/java/com/funeat/tag/persistence/TagRepository.java
- backend/src/main/java/com/funeat/tag/presentation/TagApiController.java
- backend/src/main/java/com/funeat/tag/presentation/TagController.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/tag/TagAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/tag/TagSteps.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
- backend/src/test/java/com/funeat/tag/persistence/TagRepositoryTest.java
- close #156 
- 태그 타입에 맞게 태그 목록을 리스트로 반환하도록 구현
- 태그 타입 : `TASTE`, `PRICE`, `ETC`
- 태그 타입에 맞게 태그 목록을 그룹화 하고 모든 태그 목록을 반환하도록 구현
- 관련 repository 테스트 추가
- 관련 인수 테스트 추가
- **DTO 패키지 위치**
- 기존 TagDto 클래스의 위치를 domain 패키지 -> dto 패키지로 이동
- _현재 product 관련 dto 패키지는 `product.dto`에 위치하는데, review 관련 dto 패키지는 `review.presentation.dto`에 위치함_
- **service 테스트 관련**
- 다른 조회 기능들처럼 이번에 구현한 전체 태그 목록 조회 service 메서드도 특별한 비즈니스 로직 없이 단순 조회만 반복하고 있다고 생각해서 repository 테스트만 작성하고 service 테스트는 추가하지 않았습니다.
- 이 부분에 대해서 어떻게 생각하시나요??
- **성능 관련**
- 일단 태그 타입 수만큼 조회를 하도록 간단하게 구현했는데, 여기서 성능을 더 개선할 방법이 있을까요??
- 추정 시간 : 1h
- 걸린 시간 : 2h
> [BE] feat: 전체 태그 목록 조회 기능 추가

- frontend/src/components/Common/CategoryMenu/CategoryMenu.tsx
- frontend/src/components/Review/StarRate/StarRate.tsx
- frontend/src/pages/ProductDetailPage.tsx
- close #166
닫는 태그의 불일치
mock 데이터 미사용
두가지의 충돌을 해결하였습니다.
또, category button이 안먹는 에러가 있었는데요.
이거는 css가 적용이 안돼서 그런거였습니다!
styled로 옮기니까 정상 작동!
bottom sheet가 2개여서 역시나 에러가 납니다...
리뷰 작성하기 버튼을 누르면 정렬 바텀시트가 열리네여...
일단 모달 하나만 다른 곳으로 옮기거나 ref랑 상태를 각 모달마다 따로 주는 (이건 똑똑이 말이어서 좀 찾아봐야 할 듯) 방법이 있습니다.
<똑똑이의 추천 방법>
이렇게 하면 bottom sheet 하나로 가능. 하지만 코드가 좀 더러워짐. 대충 해서 그런지 닫는 애니메이션이 또 안 먹는 느낌임.
```js
const [activeSheet, setActiveSheet] = useState<'registerReview' | 'sortOption' | null>(null);
const handleOpenRegisterReviewSheet = () => {
setActiveSheet('registerReview');
handleOpenBottomSheet();
};
const handleOpenSortOptionSheet = () => {
setActiveSheet('sortOption');
handleOpenBottomSheet();
};
const handleCloseSpecificBottomSheet = () => {
setActiveSheet(null);
handleCloseBottomSheet();
};
```
좋은 방안이 있으면 얘기해주세요. …
> [FE] 충돌 해결

- frontend/src/hooks/product/useCategoryProducts.ts
- frontend/src/hooks/product/useProductReview.ts
- frontend/src/hooks/useGet.ts
- frontend/src/pages/ProductListPage.tsx
- close #130
-  상품 목록 정렬 기능 추가
- `useGet`에서 dependency를 여러개 가질 수 있어서 배열로 수정했습니다. (없는 경우는 그냥 똑같이 안 써주면 됩니다. 근데 하나만 있는 경우에는 `[dependency]` 이렇게 써줘야돼요.)
x
x
- 추정 시간 : 2시간
- 걸린 시간 : 30분
> [FE] feat: 상품 목록 정렬 기능 API 연결

- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #104 
- 이미 정렬 기능이 구현되어 있으므로 테스트만 추가되었습니다.
- 현재 동시에 리뷰를 등록하면 ID 순으로 내림차순으로 설정하는 인수 테스트가 추가하려면 테스트를 위한 생성자를 추가해야합니다.
관련 코드는 [ed276df](https://github.com/woowacourse-teams/2023-fun-eat/pull/171/commits/ed276dffb8c4d6179d55c8fe47303df75b3b2510) 이걸 확인하면 됩니다.
x
- 추정 시간 : 0.5
- 걸린 시간 : ?
> [BE] test: 특정 상품에서 최신순으로 리뷰 목록을 조회하는 테스트 추가

- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
- backend/src/main/java/com/funeat/tag/dto/TagDto.java
- close #173 
- 리뷰 목록 페이징 요청시 500 에러가 나와서 해결했습니다. Tag를 반환해서 TagDto를 반환하도록 수정했어요
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.5
> [BE] fix: 정렬된 리뷰 목록 페이징 요청시 API가 정상적으로 응답하도록 수정

- frontend/src/components/Layout/DetailLayout.tsx
- frontend/src/components/Layout/index.ts
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/router/App.tsx
- frontend/src/router/index.tsx
- close #181 
- 상세 페이지 레이아웃 추가(헤더만 있는 레이아웃)
x
- 추정 시간 : 0.5시간
- 걸린 시간 : 10분
> [FE] feat: 상세 레이아웃 추가

- backend/src/main/java/com/funeat/common/WebConfig.java
- close #189 
- CORS 설정
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.01
> [BE] feat: CORS 설정 추가

- backend/src/main/java/com/funeat/member/application/MemberService.java
- backend/src/main/java/com/funeat/member/domain/Member.java
- backend/src/main/java/com/funeat/member/dto/MemberRequest.java
- backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
- backend/src/main/java/com/funeat/member/presentation/MemberController.java
- backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
- backend/src/test/java/com/funeat/member/domain/MemberTest.java
- close #184 
- 닉네임, 프로필사진을 가지고 오면 내용을 수정하는 로직을 추가했습니다.
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 0.8
> [BE] feat: 회원 정보를 수정하는 기능 추가

- backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
- backend/src/main/java/com/funeat/common/WebConfig.java
- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
- backend/src/main/java/com/funeat/review/presentation/ReviewController.java
- backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
- backend/src/main/java/com/funeat/review/presentation/dto/ReviewFavoriteRequest.java
- backend/src/test/java/com/funeat/acceptance/common/LoginSteps.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #196 
- 리뷰 좋아요, 리뷰 작성 기능에 로그인 기능을 붙였습니다.
> 2023-08-01 19:40:57.040  WARN 95380 --- [o-auto-1-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `com.funeat.review.presentation.dto.ReviewFavoriteRequest` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.funeat.review.presentation.dto.ReviewFavoriteRequest` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)<EOL> at [Source: …
> [BE] feat: 리뷰 작성과 리뷰 좋아요 기능에 로그인 붙이기

- backend/src/main/java/com/funeat/auth/dto/LoginInfo.java
- backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
- backend/src/main/java/com/funeat/auth/presentation/AuthController.java
- backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
- backend/src/main/java/com/funeat/auth/util/MemberHandlerInterceptor.java
- backend/src/main/java/com/funeat/common/WebConfig.java
- backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
- backend/src/main/java/com/funeat/member/presentation/MemberController.java
- backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
- backend/src/main/java/com/funeat/review/presentation/ReviewController.java
- backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- close #213 
- 사용자 정보를 조회, 수정할 때, 프론트엔드에서 쿠키를 보내는 것으로 유저를 파악하게 합니다. 이전까지는 memberId였는데, 프론트에서 memberId를 모르므로 JSESSIONID를 통해 파악해야해요.
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.6
> [BE] refactor: 사용자 정보 조회, 수정 요청을 할 때, 쿠키를 통해 사용자를 파악할 수 있도록 수정

- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/product/dto/ProductReviewCountDto.java
- backend/src/main/java/com/funeat/product/dto/RankingProductDto.java
- backend/src/main/java/com/funeat/product/dto/RankingProductsResponse.java
- backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
- backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
- backend/src/main/java/com/funeat/product/presentation/ProductController.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
- backend/src/test/java/com/funeat/product/application/ProductServiceTest.java
- backend/src/test/java/com/funeat/product/domain/ProductTest.java
- backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
- close #142 
$$
RankingScore = AvgRating - (AvgRating - 3.0)*2^{-log_{10}(Total Reviews + 1)}
$$
- `1.0 ~ 5.0`의 AvgRating이 나오게 되므로 그 중간에 있는 `3.0`을 기준으로 기준치 선정
- 평점이 `3.0` 보다 큰 상품에 대해서만 랭킹에 포함될 수 있도록 정책 변경
- `ProductRepository`의 `findAllProductsAndReviewCountByAverageRatingGreaterThan3()` 메서드 명 이대로 괜찮은가..!
- `ProductService`에서 stream 한 번만 돌면서 각 Product의 랭킹 점수 구하고, 내림차순 정렬해서 상위 3개에 해당하는 dto 구하도록 했는데 괜찮나용
- `Product` 도메인에서 랭킹 점수를 구하는 비즈니스 로직을 처리하도록 하기 위해, `ProductReviewCountDto`에서 `Product` 엔티티를 필드로 가지도록 했는데 괜찮은지..!
- 추정 시간 : 2h
- 걸린 시간 : 4h
> [BE] feat: 상품 랭킹 기능 추가

- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/presentation/dto/ReviewCreateRequest.java
- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- close #273 
- ReviewFavorite 생성 시 favorite 필드 매핑
- x
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1
> [BE] fix: 리뷰 좋아요 시 NPE 발생 수정

- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
- backend/src/main/java/com/funeat/review/presentation/dto/SortingReviewDto.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #290 
- 로그인된 회원 기준으로 좋아요 조회되게 수정
- x
- x
- 추정 시간 : 0.2
- 걸린 시간 : 0.2
> [BE] fix: 로그인된 회원 기준으로 좋아요 조회되게 수정

- backend/src/main/java/com/funeat/member/application/MemberService.java
- backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
- backend/src/test/java/com/funeat/member/application/TestMemberService.java
- close #298 
- 1. 트랜잭션 전파 옵션을 REQUIRES_NEW로 설정합니다.
- 2. 테스트에서는 REQUIRES_NEW를 하면 서비스 테스트만 새로운 트랜잭션이 생성되어서 테스트가 불가능합니다.
그래서 기존 서비스를 상속하는 테스트용 서비스를 제작하여 REQUIRES_NEW인 테스트만 `@Transactional`로 변경했습니다.
- x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.5
> [BE] fix: 트랜잭션 전파 옵션을 설정

- frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
- frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
- frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
- frontend/src/components/Review/ReviewTagList/ReviewTagList.tsx
- frontend/src/components/Review/ReviewTextarea/ReviewTextarea.tsx
- frontend/src/components/Review/StarRate/StarRate.tsx
- frontend/src/hooks/useEnterKeyDown.ts
- close #226 
리뷰 작성 페이지의 웹 접근성을 고려하였습니다.
스크린 리더 외에도 키보드만으로 작성이 가능하도록 구현하였습니다.
현재 별점을 클릭했을 때 바로 알려주는 기능과 (아마 대한항공처럼 polite나 assertive 쓰면 될 거 같음. 근데 제대로 작동할 지 모름)
태그 더보기 버튼을 클릭했을 때 추가된 태그로 포커스가 가는 기능은 황펭이 이어서 작업해줄 예정입니다.
태그 읽을 때 이모지는 안 읽게 하는 건 실패했습니다.
막 '도넛 단짠단짠' 이렇게 읽는데 이게 백에서 태그 이름이 내려오는거다보니 우리가 처리할 수 있는 방법이 안 떠오르더라구요.
근데 또 아이폰에서는 이모지도 읽어준다는 이야기를 듣고 굳이 안 읽게 만들어야하나 생각도 드네요?
x
- 추정 시간 : 2시간
- 걸린 시간 : 2시간
> [FE] feat: 리뷰 작성 페이지 웹 접근성 고려

- backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
- close #323
- 카카오 로그인 경로를 수정했습니다. (KOE002 에러 해결)
- +) 젠킨스 환경 변수가 funeat.site가 아닌 ip주소로 되어 있어서 이것도 같이 수정헀습니다. (KOE303 에러 해결)
현재 경로
</br>
수정해야할 경로
x
x
- 추정 시간 : 0.05
- 걸린 시간 : 0.05
> [BE] fix: 카카오 로그인 경로 수정

- frontend/src/components/Review/ReviewImageUploader/ReviewImageUploader.tsx
- frontend/src/hooks/review/useReviewImageUploader.ts
- close #350 
이미지 압축을 구현하였습니다.
현재 최대 사이즈를 1MB로 해놓았습니다.
직접 7MB의 이미지를 압축해보았는데요.
1MB가 안 되게 압축이 됩니다.
저희가 1MB 이상으로 못 올리잖아요?
그래서 강제로 막는건 있어야할 거 같아서 5MB로 막아놓았습니다.
5MB const MAX_SIZE = 5120 * 5120; 이거 맞나요?
그냥 1024에 5 곱했음...
x
- 추정 시간 : 4시간
> [FE] feat: 이미지 압축 구현

- frontend/src/components/Product/ProductList/ProductList.tsx
- frontend/src/hooks/useIntersectionObserver.ts
- frontend/src/mocks/handlers/reviewHandlers.ts
- close #363 
- `isLastPage` 랑 `hasNextPage` 랑 혼동되어 있어 조건을 수정했습니다.
- `isInitial` 선언했던것 때문에 안되는 것 같아서 삭제했습니다.
x
x
- 추정 시간 :
- 걸린 시간 : 0.5
> [FE] fix: 상품 상세 페이지에서 무한스크롤 안되는 버그 수정

- backend/src/main/java/com/funeat/member/domain/Member.java
- backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
- backend/src/main/java/com/funeat/member/persistence/RecipeFavoriteRepository.java
- backend/src/main/java/com/funeat/product/persistence/ProductRecipeRepository.java
- backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
- backend/src/main/java/com/funeat/recipe/application/RecipeService.java
- backend/src/main/java/com/funeat/recipe/domain/Recipe.java
- backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
- backend/src/main/java/com/funeat/recipe/dto/ProductRecipeDto.java
- backend/src/main/java/com/funeat/recipe/dto/RecipeAuthorDto.java
- backend/src/main/java/com/funeat/recipe/dto/RecipeCreateRequest.java
- backend/src/main/java/com/funeat/recipe/dto/RecipeDetailResponse.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeImageRepository.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
- backend/src/test/java/com/funeat/acceptance/common/AcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
- backend/src/test/java/com/funeat/member/persistence/RecipeFavoriteRepositoryTest.java
- backend/src/test/java/com/funeat/product/persistence/ProductRecipeRepositoryTest.java
- backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
- backend/src/test/java/com/funeat/recipe/persistence/RecipeImageRepositoryTest.java
- close #354 
꿀조합 상세 정보 조회 기능
**Interceptor의 PathPattern**
현상태 : `/api/recipes`로 들어오는 요청이고 `GET`이 아니면 RecipeHandlerInterceptor 작동
- `Review` 형식에 맞춰서 `Recipe`에도 `FavoriteCount` 추가
- `Recipe`의 `name` 필드를 `title`로 수정
- 추정 시간 : 3
- 걸린 시간 : 3.5
> [BE] feat: 꿀조합 상세 정보 조회 기능

- frontend/.storybook/preview-body.html
- frontend/src/components/Common/Svg/SvgIcon.tsx
- frontend/src/components/Common/Svg/SvgSprite.tsx
- frontend/src/components/Members/MembersTitle/MembersTitle.tsx
- frontend/src/components/Members/MembersTitle/MyPageTitle.stories.tsx
- frontend/src/components/Product/PBProductList/PBProductList.tsx
- frontend/src/mocks/data/members.json
- frontend/src/pages/ProfileModifyPage.tsx
- frontend/src/router/index.tsx
- close #392 
프로필의 타이틀 컴포넌트를 구현하였습니다.
SectionTitle이랑 구조 비슷하게 구현하였습니다.
x
- 추정 시간 : 1시간
- 걸린 시간 : 1시간 반
> [FE] feat: 프로필 타이틀 컴포넌트 구현

- frontend/src/components/Memebers/MembersTitle/MembersTitle.stories.tsx
- frontend/src/components/Memebers/MembersTitle/MembersTitle.tsx
- close #405
memberTitle 컴포넌트를 구현하였습니다.
페이지 더 붙이고 구체적인 내용을 덧 붙일 예정입니다.
title props로 받는건 추후 api 논의 후 달라질 듯 합니다.
마크업만 봐주세요!
x
x
- 추정 시간 : 2시간
- 걸린 시간 : 20분
> [FE] feat: MemberTitle 컴포넌트 구현

- frontend/src/components/Common/Input/Input.stories.tsx
- frontend/src/components/Common/Input/Input.tsx
- close #423 
- 꿀조합에서 사용된 상품을 추가할 때 6개 이상 입력 할 수 없도록 Input을 disabled 시킬 예정입니다. 따라서 해당 속성에 대한 스타일을 추가했습니다.
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분
> [FE] feat: Input disabled 속성의 스타일 추가

- frontend/src/pages/HomePage.tsx
- frontend/src/service/channelTalk.ts
- close #432
채널톡을 구현하였습니다.
현재 env 파일에 key를 넣었는데 젠킨스에 넣어야 한다고 하네용
그래서 아마 merge 되도 안 뜰 듯??
참고로 channelTalk.ts는 채널톡 페이지에 있는 거 그대로 가져왔는데 any가 있구요...
```js
// eslint-disable-next-line prefer-rest-params
ch.c?.(arguments);
````
여기에 arguments도 저 주석을 안하면 사용을 못해서 이렇게 씁니도...
위치는 데스크톱에는 
이렇게 떠요. ㅠ
이게 커스텀 할 수 있대서 해봤는데, 안 먹습니다.
내부 홈페이지에서 옮겼는데 그거는 한계가 있습니다.
그래서 결론은 위치가 어쩔 수가 없어요 🥲
그냥 모바일 기준으로만 맞췄습니다!
x
- 추정 시간 : 2시간
- 걸린 시간 : 1시간
> [FE] feat: 채널톡 구현

- backend/src/main/java/com/funeat/recipe/domain/Recipe.java
- backend/src/main/java/com/funeat/recipe/dto/RecipeAuthorDto.java
- backend/src/main/java/com/funeat/recipe/dto/RecipeDetailResponse.java
- backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
- close #415
- Recipe에 `createdAt` 컬럼 추가
- 꿀조합 상세 조회 api 반환값 수정
- `nickName` -> `nickname`
- `createdAt` 필드 추가
X
- DB에 접속해서 Recipe에 `createdAt` 필드 추가 하겠습니다.
- 추정 시간 : 0.5
- 걸린 시간 : 0.5
> [BE] feat: Recipe에 생성 시간 추가

- backend/src/main/java/com/funeat/common/WebConfig.java
- backend/src/main/java/com/funeat/member/dto/MemberReviewDto.java
- backend/src/main/java/com/funeat/member/dto/MemberReviewsResponse.java
- backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
- backend/src/main/java/com/funeat/member/presentation/MemberController.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
- backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #418 
- 사용자 마이페이지 접속 시 해당 사용자 리뷰 조회 기능 추가입니다.
- x
- x
- 추정 시간 : 2
- 걸린 시간 : 3
> [BE] feat: 사용자 마이페이지 리뷰 조회 기능 구현

- frontend/src/components/Recipe/RecipeList/RecipeList.tsx
- frontend/src/hooks/queries/recipe/index.ts
- frontend/src/hooks/queries/recipe/useInfiniteRecipesQuery.ts
- frontend/src/mocks/handlers/recipeHandlers.ts
- frontend/src/mocks/handlers/reviewHandlers.ts
- frontend/src/mocks/handlers/utils.ts
- frontend/src/pages/RecipePage.tsx
- frontend/src/types/common.ts
- close #448 
- 꿀조합 전체 목록 조회 infinite query 추가
- 꿀조합 요청 무한스크롤 추가
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 1시간
> [FE] feat: 꿀조합 전체 목록 조회 요청 쿼리 추가

- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/dto/SearchProductDto.java
- backend/src/main/java/com/funeat/product/dto/SearchProductResultDto.java
- backend/src/main/java/com/funeat/product/dto/SearchProductResultsResponse.java
- backend/src/main/java/com/funeat/product/dto/SearchProductsResponse.java
- backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
- backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
- backend/src/main/java/com/funeat/product/presentation/ProductController.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
- backend/src/test/java/com/funeat/fixture/ProductFixture.java
- backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
- close #402 
- 공통 상품, PB 상품 같이 통합해서 검색하도록 구현
- `자동 완성 API`, `검색 결과 API` 분리
- 자동 완성의 경우에는 API 호출을 자주하고, 모든 상품 정보를 반환할 필요가 없음
- `자동 완성 API` : 상품 정보에서 id, name, categoryType만 반환
- `검색 결과 API` : 필요한 상품 정보 전부 반환
- 페이징 처리 (size : 10, sort : X)
```sql
SELECT *
FROM product
WHERE name LIKE '%망고%';
```
```sql
SELECT *
FROM product
WHERE name LIKE '%망고%'
ORDER BY CASE WHEN name LIKE '망고%' THEN 1 ELSE 2 END;
```
위 방식은 순서에 상관없이 '망고'라는 문자열이 포함된 상품명을 다 조회하기 때문에, 사용자의 의도에 맞는 정확한 검색과는 거리가 멀다.
=> '망고'라는 검색어로 시작하는 문자열이 먼저 출력될 수 있도록 `ORDER BY` + `CASE WHEN ~` 사용
ex)
**망고**주스
**망고**푸딩
애플**망고**
- controller에서 PageRequest 재정의하고 service로 넘겨주는 이유
- `CustomPageableHandlerMethodArgumentResolver`로 인해서 `Pageable`에 id로 정렬하는 sort 옵션이 기본으로 들어가있음
- 따라서 `ORDER BY` 절을 포함시켜서 쿼리를 날리게 되는데, 위 `ORDER BY` 절과 중복돼서 에러 발생
=> …
> [BE] feat: 상품 검색 기능 구현

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
- close #461
- DEV, PROD 서버 분리로 인해 카카오 로그인 부분 환경 변수를 분리합니다.
- application-local.yml에 추가 필요한지 확인해주세요
x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1
> [BE] fix: DEV, PROD, LOCAL 카카오 로그인 환경변수 분리

- frontend/src/components/Search/RecommendList/RecommendList.tsx
- frontend/src/hooks/search/useSearch.ts
- frontend/src/pages/SearchPage.tsx
- close #464 
- 검색어 앞, 뒤 공백 제거 후 요청
- 자동 완성 클릭 시 해당 상품으로 검색
- 검색 페이지 진입 시 검색창 포커스
- 검색창 placeholder 수정
- 상품 검색 시 '상품 이름을 검색해보세요.'
- 꿀조합 검색 시 '꿀조합에 포함된 상품을 입력해보세요.'
- 모바일에서 자동완성 창 안 뜨는 버그 해결 (바텀시트와 같은 이슈... fit-content....)
x
- 빠진 부분 있음 말해주십셔
- 추정 시간 : 2시간
- 걸린 시간 : 2시간
> [FE] refactor: 검색 페이지 이슈 수정

- backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/member/exception/MemberErrorCode.java
- backend/src/main/java/com/funeat/member/exception/MemberException.java
- backend/src/main/java/com/funeat/recipe/application/RecipeService.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
- close #329
- 리뷰(`likeReview`)랑 레시피(`likeRecipe`)에 비관적 락을 걸었습니다.
- X Lock은 성능상 좋지 않으므로 레벨 4에서 스케줄러로 수정할 예정
- 리뷰좋아요(`ReviewFavorite`), 레시피좋아요(`RecipeFavorite`)는 유니크 제약 조건 추가했습니다.
- DB에 유니크 제약 조건 추가하면 될 것 같아요
- x
- 낙관적 락 적용시 500개 좋아요가 동시에 들어오면 50개~60개만 처리됩니다. (`likeReview` 기준)
- 추정 시간 : 모름
- 걸린 시간 : 48
> [BE] fix: 리뷰, 레시피 좋아요 데드락, 동시성 이슈 수정

- backend/src/main/java/com/funeat/recipe/application/RecipeService.java
- backend/src/main/java/com/funeat/recipe/dto/SearchRecipeResultDto.java
- backend/src/main/java/com/funeat/recipe/dto/SearchRecipeResultsResponse.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
- backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
- close #457 
- 검색어(상품 명)를 기준으로 해당 상품이 포함된 꿀조합들 검색
- 상품 검색 기능처럼 `LIKE` 연산
- 페이징 처리 (size : 10, sort : X)
- X
- X
- 추정 시간 : 4h
- 걸린 시간 : 2.5h
> [BE] feat: 꿀조합 검색 기능 구현

- frontend/src/components/Product/ProductRecipeList/ProductRecipeList.tsx
- frontend/src/components/Product/index.ts
- frontend/src/hooks/queries/product/index.ts
- frontend/src/hooks/queries/product/useInfiniteProductRecipesQuery.ts
- frontend/src/mocks/handlers/recipeHandlers.ts
- frontend/src/mocks/handlers/reviewHandlers.ts
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/types/common.ts
- close #453
- 상품 상세 페이지 꿀조합 탭 UI, 쿼리 추가
- 상품을 사용한 꿀조합이 없을 때 작성하러 가라고 하고 싶어요. 꿀조합 작성 바텀시트를 상세 페이지에서 띄우기에 페이지에서 하는 일이 많아질 것 같아 우선 꿀조합 페이지 링크를 추가했습니다. 좋은 의견 주세요.!
|||
|--|--|
|![스크린샷 2023-08-17 오전 1 11 07](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/d23bef7d-e67f-4e0a-aa46-bfb3f41bb406)|![스크린샷 2023-08-17 오전 1 11 55](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/c3a776de-1740-412b-822e-f1d3ff1656e6)|
- 추정 시간 : 4시간
- 걸린 시간 : 2시간
> [FE] feat: 상품 상세 페이지 꿀조합 탭 구현

- backend/src/main/java/com/funeat/recipe/application/RecipeService.java
- backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
- backend/src/main/java/com/funeat/recipe/dto/RankingRecipesResponse.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
- backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
- close #486 
- 좋아요 내림차순으로 TOP 3 꿀조합 목록 반환
- TOP 3 태그 조회 기능과 마찬가지로 Repository 메서드에 `PageRequest.of(0, 3)`를 파라미터로 넘겨주는 방식으로 상위 3개 조회하도록 구현
- X
- X
- 추정 시간 : 2h
- 걸린 시간 : 1.5h
> [BE] feat: 꿀조합 랭킹 기능 구현

- frontend/src/components/Recipe/RecipeItem/RecipeItem.tsx
- frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
- frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
- close #498
하트 색을 빨간색으로 변경하였습니다.
실패 시에도 폼을 비우고 닫도록 하였습니다.
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분
> [FE] feat: 하트 색 살리기와 실패 시에도 폼 비우기

- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
- backend/src/main/java/com/funeat/product/presentation/ProductController.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/product/ProductSteps.java
- backend/src/test/java/com/funeat/product/persistence/ProductRecipeRepositoryTest.java
- backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
- close #487 
- 상품으로 해당 상품이 포함된 꿀조합 목록 조회하는 기능 구현
- `ProductService` vs `RecipeService`
- 상품 상세 정보 페이지에서 해당 상품의 꿀조합 목록을 조회하는 기능이고, uri도 `ProductController`에 가깝다고 생각해서 `ProductController` - `ProductService`로 구현했습니다.
- `ProductRecipeRepository` vs `RecipeRepository` vs `ProductRepository`
- `ProductRecipeRepository` : 여기에서 처리하는 게 맞다고 생각했는데, 좋아요순 정렬을 할 때 favoriteCount를 ProductRecipe 엔티티에서 찾을 수 없어서 다른 repository로 옮겼습니다.
- `RecipeRepository` vs `ProductRepository` : Recipe를 반환하기 때문에 RecipeRepository에서 처리하도록 했는데 어떻게 생각하시나요?
- X
- 추정 시간 : 2h
- 걸린 시간 : 1.5h
> [BE] feat: 특정 상품의 꿀조합 목록 조회 기능 구현

- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- close #509 
- 꿀조합 검색 시 중복 제거
- DISTINCT 구문 추가해서 해결
- But, DISTINCT랑 ORDER BY 같이 사용 불가
- 대안 1) ORDER BY 절에 MIN, MAX 등 사용 => ORDER BY CASE WHEN ~ 으로 처리하고 있기 때문에 현재 우리 상황과 다름
- 대안 2) ORDER BY 절 제거 => 자동 완성에서 사용하기 위한 ORDER BY 절이었고, 이미 자동 완성을 거친 후여서 없어도 괜찮다고 판단. 꿀조합 검색에서 상품명의 순서는 중요하지 않다고 생각
- 대안 2 선택
- 위에 대안으로 적어둔 내용 확인해주세요.
- X
- 추정 시간 : 15min
- 걸린 시간 : 30min
> [BE] fix: 꿀조합 검색 시 중복 검색되는 버그 해결

- frontend/src/components/Common/ScrollButton/ScrollButton.tsx
- frontend/src/pages/RecipePage.tsx
- close #516 
꿀조합 버튼을 100%로 만들고, 스크롤 버튼을 꿀조합 페이지일 때만 위로 올렸습니다.
그리고 꿀조합 버튼의 뒷 배경을 주어 보이지 않도록 하였습니다.
- 추정 시간 : 1시간
- 걸린 시간 : 30분
> [FE] refactor: 꿀조합 버튼 변경

- backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
- backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
- close #549 
- `검색어로 시작되는 단어 우선`을 먼저 하고, `id 내림차순 정렬` 적용
- **ORDER BY** 절에서 `p.id DESC`를 뒤로 이동
- https://github.com/woowacourse-teams/2023-fun-eat/issues/536 
해당 이슈는 `CASE WHEN ~` 부분만 정렬 조건이었기 때문에 페이징이 넘어갈 때마다 전체 정렬을 다시 하는데, 저 조건이 동일한 경우 이후에는 랜덤 정렬됨
- 따라서 `CASE WHEN ~`으로도 정렬하고, 이후 정렬 조건으로 id도 줘야 함.
- X
- X
- 추정 시간 : 20min
- 걸린 시간 : 20min
> [BE] 검색 정렬 우선 순위 반대로 적용중 버그 해결

- backend/src/test/java/com/funeat/fixture/CategoryFixture.java
- backend/src/test/java/com/funeat/product/persistence/CategoryRepositoryTest.java
- close #535
- 세븐일레븐 테스트 데이터를 추가합니다.
- 노션에 내일 아침에 쿼리 추가할거 남겼어요
- CU, GS25 신상품 추가해야함
- [문제점]: NEW 태그가 붙어있는데, 이미 예전에 추가한 상품들도 존재해서 일일이 존재하는지 검사하면서 쿼리 추가 필요
- 신상품이 몇 개 없을줄 알고 다 추가하려고 했는데, 너무 많아서 필요한 것만 노션에 적음
- x
- 추정 시간 : 3? 4?
- 걸린 시간 : 3
> [BE] feat: 세븐일레븐 테스트 데이터 추가

- frontend/src/components/Common/ScrollButton/ScrollButton.tsx
- close #545 
scroll button bottom 이동하였습니다.
채널톡 버튼은 옮기기 힘들어서 둘의 순서를 바꾸었습니다.
x
x
- 추정 시간 : 1시간
- 걸린 시간 : 1분
> [FE] refactor: scroll button bottom 이동

- backend/src/main/java/com/funeat/auth/application/AuthService.java
- backend/src/main/java/com/funeat/auth/presentation/AuthApiController.java
- backend/src/main/java/com/funeat/auth/presentation/AuthController.java
- backend/src/main/java/com/funeat/auth/util/AuthArgumentResolver.java
- backend/src/main/java/com/funeat/auth/util/AuthHandlerInterceptor.java
- backend/src/main/java/com/funeat/recipe/util/RecipeDetailHandlerInterceptor.java
- backend/src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
- backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
- backend/src/test/resources/application.yml
- close #564 
1. 중요 사항
- `request.getSession(create = false)`를 통해 세션이 존재하지 않으면 새로운 세션이 생성되지 않도록 합니다.
- 로그아웃시 클라이언트에 저장된 쿠키도 삭제되도록 변경했습니다
- 클라이언트에게 보내주는 쿠키 이름을 `JSESSIONID`에서 `FUNEAT`으로 변경했습니다
2. 리팩터링
- `session == null`을 `Objects.isNull(session)`으로 한 번 감싸주는 로직으로 변경했습니다.
- `interceptor`, `argument resolver`에 `final` 추가했습니다
- 테스트쪽에 사용되지 않는 변수가 있어서 메서드 호출만 하도록 변경했습니다
- JSESSIONID 이름도 바꿀 수 있는데, 다른 이름으로 변경하는건 어떤가요? → `FUNEAT`으로 변경
- x
- 추정 시간 : 0.5
- 걸린 시간 : 2
> [BE] feat: 로그인 정보가 존재하지 않을 때, 새로운 세션을 생성하지 않도록 하는 설정 추가

- frontend/package.json
- frontend/public/index.html
- frontend/src/hooks/common/index.ts
- frontend/src/hooks/common/useRouteChangeTracker.ts
- frontend/src/index.tsx
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/router/App.tsx
- frontend/yarn.lock
- close #566
- 황펭이 알려준 https://github.com/codler/react-ga4 라이브러리를 사용했습니다.
- `useRouteChangeTracker` hook을 통해 페이지 이동이 일어나는 것을 추적하게 됩니다.
x
현재 테스트로 카테고리 선택하는 버튼에 이벤트를 달아놨습니다!
- 추정 시간 : 2
- 걸린 시간 : 2
> [FE] feat: 구글 애널리틱스 js에서 처리하도록 이동

- frontend/package.json
- frontend/src/hooks/common/useImageUploader.ts
- frontend/src/index.tsx
- frontend/yarn.lock
- close #581 
- S3클라이언트에 region 추가
x
- 생각해보니 젠킨스에 환경변수 설정을 안했네요 ㅎㅎ..
- 추정 시간 :
- 걸린 시간 :
> [FE] fix: S3 이미지 업로드 수정

- backend/src/main/java/com/funeat/member/domain/favorite/RecipeFavorite.java
- backend/src/main/java/com/funeat/member/domain/favorite/ReviewFavorite.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/product/domain/ProductRecipe.java
- backend/src/main/java/com/funeat/recipe/domain/Recipe.java
- backend/src/main/java/com/funeat/recipe/domain/RecipeImage.java
- backend/src/main/java/com/funeat/recipe/persistence/RecipeRepository.java
- backend/src/main/java/com/funeat/review/domain/Review.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
- close #584 
- `@ManyToOne`의 디폴트 FetchType인 EAGER를 LAZY로 수정
- X
LAZY 설정 후 `RecipeAcceptanceTest`의 `레시피의_상세_정보를_조회한다` 테스트 실패
- 문제 원인
- Recipe의 `@ManyToOne` 매핑 필드였던 Member를 Lazy Loading으로 수정
- recipeRepository.findById(recipeId); 의 결과에 Member 세팅 X
- member가 필요한 파트(RecipeDetailResponse.toResponse)에서 LazyInitializationException 발생
- 해결 : Member를 fetchJoin으로 Recipe와 함께 가져오는 `findRecipeWithMemberById` 메소드 생성
- 해당 테스트에 `@Transactional`을 붙여 LazyInitializationException은 피할 수 있지만, RestAssured 특성상 테스트 트랜잭션과 RestAssured 트랜잭션이 분리되어 또다른 문제 발생
- 추정 시간 : 15m
- 걸린 시간 : 1h
> [BE] refactor: @ManyToOne의 FetchType을 LAZY로 수정

- backend/src/main/java/com/funeat/common/logging/Logging.java
- backend/src/main/java/com/funeat/common/logging/LoggingAspect.java
- backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
- backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
- close #563
- Spring AOP를 통해 API에 대한 로깅 기능을 추가했습니다.
- 로그로 남겨두고 싶은 곳에 `@Logging`을 사용하면 됩니다.
- 로깅하지 않는 내용
- 이미지 파일 - 이미지는 직렬화 불가 + 회의를 통해 이미지 이름도 로깅하지 않도록 함 (아래에 회의 내용 적음)
- HttpServletRequest - 현재 `AuthController`만 파라미터로 가지고 있는데, 다른 데이터를 로깅할 상황이 있을 수도 있으므로 + 실수 방지
- 현재 데이터 추가 / 생성에 대한 API만 적용해야해서 이게 5개뿐이라 `@Logging`을 적용했습니다.
- 나중에 로깅할 곳이 더 많아지면 `@NoLogging`으로 바꾸면 됩니다.
---
[1] Spring AOP
- `Aspect` 클래스 하나로 관리 가능
- `@Logging`을 통해 로깅하고 싶은 메서드만 추가해주면 되서 유지보수하기 좋음
[2] Log4Jdbc (2013년이 최신 버전)
- `Log4Jdbc`를 사용하려면 `datasource driver-class-name`, `url`을 형식에 맞게 수정해야합니다
- `logback xml`에서 설정을 해주면 모든 쿼리문을 로깅할 수 있습니다. 근데 특정 쿼리문만 로깅하려면 따로 자바 코드를 추가해야한다고 합니다.
- 간단하게 적용해보니 관리 포인트가 `Spring AOP`보다 많아져서 패스
[3] Janino
- `logback`에서 조건부 처리를 할 수 있다고 합니다.
- 라이브러리 소개가 자바 코드를 바이트 코드로 빠르게 변환하는 컴파일러 라이브러리라서 목적에 맞지 …
> [BE] API에 대한 로깅 기능 추가

- frontend/public/mockServiceWorker.js
- frontend/src/components/Members/MemberModifyInput/MemberModifyInput.tsx
- frontend/src/components/Members/index.ts
- frontend/src/components/Recipe/RecipeNameInput/RecipeNameInput.tsx
- frontend/src/pages/MemberModifyPage.tsx
- close #611 
- 꿀조합 이름, 닉네임 글자수 제한
- 우선 max length로 입력 막았습니다.
- 추후 폼과 인풋 예외처리가 필요해요. 프론트에서도 한번 걸러줘야 합니다.!
x
- 추정 시간 : 
- 걸린 시간 :
> [FE] fix: 꿀조합 이름, 닉네임 글자수 제한

- backend/src/main/java/com/funeat/FuneatApplication.java
- backend/src/main/java/com/funeat/auth/presentation/AuthController.java
- backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
- backend/src/main/java/com/funeat/common/CustomPageableHandlerMethodArgumentResolver.java
- backend/src/main/java/com/funeat/common/WebConfig.java
- backend/src/main/java/com/funeat/common/s3/S3Uploader.java
- backend/src/main/java/com/funeat/exception/presentation/GlobalControllerAdvice.java
- backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
- backend/src/main/java/com/funeat/member/dto/MemberReviewDto.java
- backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
- backend/src/main/java/com/funeat/member/presentation/MemberController.java
- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
- backend/src/main/java/com/funeat/product/presentation/ProductApiController.java
- backend/src/main/java/com/funeat/product/presentation/ProductController.java
- backend/src/main/java/com/funeat/recipe/dto/RankingRecipeDto.java
- backend/src/main/java/com/funeat/recipe/presentation/RecipeController.java
- backend/src/main/java/com/funeat/recipe/util/RecipeHandlerInterceptor.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/java/com/funeat/review/domain/Review.java
- backend/src/main/java/com/funeat/review/domain/ReviewTag.java
- backend/src/main/java/com/funeat/review/dto/RankingReviewDto.java
- backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
- backend/src/main/java/com/funeat/review/presentation/ReviewController.java
- backend/src/main/resources/application-local.yml
- backend/src/test/java/com/funeat/FuneatApplicationTests.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
- backend/src/test/java/com/funeat/recipe/persistence/RecipeRepositoryTest.java
- close #627 
- 코드 포맷 전체적으로 돌림
- `Controller`, `ApiController` 에 `final` 붙이기 + 나머지 `final` 빠진 부분 추가
- `KakaoPlatformUserProvider`에 환경변수 들어가는 부분 생성자 주입이 아닌 필드로 이동하기
- `Controller → Service`로 넘어갈 때, 파라미터로 `loginInfo.getId()`를 까서 `Long`으로 보내줌
- `ProductService`의 `getAllProductsInCategory`에 `ageable.getSort().getOrderFor(REVIEW_COUNT) != null`대신 `Objects.nonNull()`를 적용
- 여러 숫자, 문자, 리스트 상수 처리
- 사용하지 않는 메서드 삭제
- `application-local.yml`에도 s3 설정 추가
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] refactor: 코드 포맷 적용, 컨벤션 적용

- backend/src/main/java/com/funeat/product/domain/Category.java
- backend/src/main/java/com/funeat/product/dto/CategoryResponse.java
- backend/src/test/java/com/funeat/fixture/CategoryFixture.java
- backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
- close #636 
- Category 엔티티에 image 필드 추가
- 카테고리 목록 조회 시 이미지도 반환하도록 CategoryResponse 수정
X
- image가 추가되면서 CategoryFixture도 수정했습니다.
- Category 테이블에 image 컬럼 추가해야 합니다~
- 추정 시간 : 30min
- 걸린 시간 : 15min
> [BE] feat: 카테고리 이미지 추가

- frontend/src/components/Common/CategoryList/CategoryList.tsx
- frontend/src/constants/index.ts
- frontend/src/mocks/data/foodCategory.json
- frontend/src/mocks/data/storeCategory.json
- frontend/src/pages/HomePage.tsx
- frontend/src/types/common.ts
- close #635 
카테고리 api에 이미지가 추가되어 그에 맞게 로직을 수정하였습니다.
x
x
- 추정 시간 : 2시간
- 걸린 시간 : 15분
> [FE] refactor: 카테고리 로직 수정

- frontend/src/components/Common/Carousel/Carousel.tsx
- frontend/src/components/Common/CategoryItem/CategoryItem.tsx
- frontend/src/components/Layout/DefaultLayout.tsx
- frontend/src/components/Layout/SimpleHeaderLayout.tsx
- frontend/src/pages/HomePage.tsx
- frontend/src/pages/MemberPage.tsx
- frontend/src/pages/MemberRecipePage.tsx
- frontend/src/pages/MemberReviewPage.tsx
- frontend/src/pages/RecipeDetailPage.tsx
- close #634 
- 디폴트 레이아웃에서 패딩 삭제
- 심플 헤더 레이아웃에서 패딩탑 추가
- 캐러셀 너비 수정, 인라인 스타일로 수정
- 카테고리 이름 폰트 사이즈 수정
x
- 추정 시간 : 1시간
- 걸린 시간 : 1시간
> [FE] refactor: 레이아웃 스타일 수정

- frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
- frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
- close #642 
- 추정 시간 :
- 걸린 시간 :
> [FE] fix: 리뷰, 꿀조합 작성 함수 디바운스 적용

- frontend/src/components/Product/ProductItem/ProductItem.tsx
- frontend/src/pages/HomePage.tsx
- frontend/src/pages/ProductListPage.tsx
- close #643
- 상품 이미지 비율 수정
- 상품 목록 높이 수정
- 배너 이미지에 인스타그램 링크 추가
x
x
- 추정 시간 : 10분
- 걸린 시간 : 20분
> [FE] refactor: 자잘한 디자인 수정 및 배너 링크 연결

- backend/src/main/java/com/funeat/product/domain/Product.java
- close #659
- Product의 reviewCount 자료형을 Long으로 변경
- 추후 동시성 처리 관련 논의 필요
AtomicLong의 경우 jpa를 이용해 영속화 하기 위해서는 
[AttributeConverter](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#basic-jpa-convert)를 만들거나, [Custom Type](https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#basic-custom-type)을 만들어야 한다.
ReviewCount에 AtomicLong을 도입했던 이유는 임시 동시성 제어를 위해서였는데,
해당 사항은 아직 논의가 끝나지 않았기 때문에
우선 Long으로 처리 후 논의가 끝나면 본격적인 동시성 처리를 할 예정
- 추정 시간 : 0.1
- 걸린 시간 : 0.1
> [BE] refactor: Product의 reviewCount 자료형을 Long으로 변경

- backend/src/main/java/com/funeat/common/logging/LoggingAspect.java
- close #656
- `LocalDateTime`은 `Serializable`을 가지고 있지만,  Jackson이 직렬화를 못해서 에러가 나옵니다.
- 그래서 직렬화를 할 수 있도록 `LoggingAspect.java`의 `ObjectMapper`에 `JavaTimeModule`을 추가했습니다.
Jackson이 직렬화하지 못하는 이유는 `LocalDateTime`이 Java 8 신규 기능이라 하위 호환성으로 인해 지원을 못하게 됐다고 하네요. 그래서 따로 모듈을 추가했다고 합니다.
그런데 라이브러리 찾아보면 `jackson-datatype-jdk8`도 있고, `jackson-datatype-jsr310`도 있어서 `LocalDateTime`은 `jdk8`에 있어야 하는거 아닌가 생각이 드는데요.
대충 찾아보니 Jackson이 만들어진 이후로 `java.time`처럼 완전히 새로운 패키지로 분리한건 Java 8에서 처음 발생한거라고 하네요
추가로 `jdk8`은 새로운 데이터 타입(`Optional`, `Stream`)이 추가되어서 만들어진 거라고 합니다.
- `Jdk8Module`도 있는데, 이건 `Optional`이나, `Stream` 같은걸 직렬화할 수 있다고 합니다. 이것도 추가하는게 좋을까요?
- AS-IS
```
2023-09-18 01:16:02.000  INFO 39019 --- [nio-8080-exec-3] com.funeat.common.logging.LoggingAspect  : [REQUEST GET] [PATH /api/products/1/reviews] …
```
> [BE] fix: LocalDateTime이 들어간 Response도 로깅할 수 있도록 설정

- backend/src/test/resources/application.yml
- close #652
- test 패키지에 `appliation.yml`에서 h2 데이터베이스 주소를 uuid로 하여 테스트 컨텍스트가 초기화 되어도 h2 데이터베이스 주소가 겹치지 않도록 합니다.
h2 코드 까봤는데
저기서 result를 얻는 과정에서 에러가 나옵니다.
- 계속 테스트해보니 메모리 사용량이 많을 경우 발생하는 것으로 보입니다. 제대로 된 원인은 아무리 봐도 모르겠어요.
- 추정되는건 테스트 컨택스트가 초기화 될 때, 다시 디비를 연결하던데 이 과정에서 이상이 았는 것 같습니다.
- 그래서 테스트 컨텍스트가 초기화 될 때마다 새로운 디비 주소로 연결할 수 있도록 합니다.
- 이후엔 메모리 사용량이 많은 상태에서 계속 테스트를 돌려봐도 에러가 나오질 않습니다.
- 추정 시간 : 0.5
- 걸린 시간 : 6
> [BE] fix: 테스트 컨텍스트가 초기화될 때,  새로운 테스트 환경에서 테스트하도록 설정

- backend/src/main/java/com/funeat/review/persistence/ReviewRepository.java
- backend/src/test/java/com/funeat/fixture/ReviewFixture.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #666 
- 이미지가 없는 리뷰는 좋아요가 눌러서 제일 많은 리뷰가 되어도 상품 이미지가 변경되지 않습니다.
- S3를 도입하면서 `null`로 저장되던 이미지 경로가 이후엔 `""`로 저장되어서 발생하는 문제
- 현재 디비에는 `""`로 되어서 에러가 발생해하는 부분을 `image = null`로 변경해두었습니다.
- ~~생각해보니 프론트에서도 `null`일 때 기본 이미지를 처리할 것 같은데, `""`로 같이 변경해야할 것 같아요~~ (어차피 변경 대상에 제외되어서 고려할 필요 없음)
- x
- 추정 시간 : 0.5
- 걸린 시간 : 0.5
> [BE] fix: 이미지가 없는 리뷰는 상품 이미지 변경 대상에 제외

- .github/workflows/test-fe.yml
- .github/workflows/test.yml
- close #651
- 회의한 내용대로 노드 20 버전이 필요한 버전까지 안올렸습니다.
- [올라간 버전]
- `EnricoMi/publish-unit-test-result-action@v1` → `EnricoMi/publish-unit-test-result-action@v2`
- 참고 (노드 20 버전으로 업데이트할 때)
- [공통]
- `actions/checkout@v3` → `actions/checkout@v4`
- `mikepenz/action-junit-report@v3` → `mikepenz/action-junit-report@v4`
- [프론트]
- `node-version: '18.16.1'` → `node-version: '20.x.x' (그때 버전에 맞게 수정)`
- [기타]
- 시간이 지나면 나중에 다른 곳들도 버전이 올라갈 수도 있음
`actions/checkout@v4`의 경우엔 현재 노드 20 미만의 버전을 지원하지 않는다고 합니다 ([참고](https://github.com/actions/checkout/issues/1385))
-x
- x
- 추정 시간 : 0.5
- 걸린 시간 : 1
> [ALL] Github Actions workflows 버전 관리

- frontend/src/hooks/search/useSearch.ts
- frontend/src/pages/IntegratedSearchPage.tsx
- frontend/src/pages/SearchPage.tsx
- close #674 
- 검색 결과 요청 쿼리에 debounced 값 대신 searchQuery로 변경
- 추정 시간 :
- 걸린 시간 :
> [FE] fix: 검색 결과 두 번 요청 수정

- frontend/public/index.html
- frontend/src/styles/font.ts
- frontend/src/styles/index.ts
- close #671 
폰트를 추가하고 preload 설정을 하였습니다.
디자인 시스템에서 그냥 font 파일을 도려내버렸는데요.
pretendard 관련만 지웠어야했나요?
여기서 또 따로 추가해줄게 있는건 아니죠...?
아리송하네용
https://github.com/orioncactus/pretendard
- 추정 시간 : 30분
- 걸린 시간 : 5분
> [FE] feat: 폰트 추가

- frontend/src/index.tsx
- frontend/src/pages/AuthPage.tsx
- frontend/src/pages/HomePage.tsx
- frontend/src/pages/IntegratedSearchPage.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/MemberModifyPage.tsx
- frontend/src/pages/MemberPage.tsx
- frontend/src/pages/MemberRecipePage.tsx
- frontend/src/pages/MemberReviewPage.tsx
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/pages/ProductListPage.tsx
- frontend/src/pages/RecipeDetailPage.tsx
- frontend/src/pages/RecipePage.tsx
- frontend/src/pages/SearchPage.tsx
- frontend/src/router/index.tsx
- frontend/tsconfig.json
- frontend/webpack.common.js
- frontend/webpack.prod.js
- close #677 
lazy를 적용하였습니다.
lazy를 사용한 컴포넌트의 export 방식 또한 바꾸었습니다.
bundle analyzer 추가하였습니다.
x
x
- 추정 시간 : 10분
- 걸린 시간 : 1시간
> [FE] feat: lazy 적용

- frontend/src/pages/RecipePage.tsx
- close #688
- 꿀조합 페이지 디자인 수정
스크롤 내릴 때 정렬버튼은 안내려오게 수정
x
x
- 추정 시간 : 
- 걸린 시간 : 10분
> [FE] feat: 꿀조합 페이지 디자인 수정

- frontend/src/components/Common/CategoryFoodList/CategoryFoodList.tsx
- frontend/src/components/Common/CategoryFoodTab/CategoryFoodTab.tsx
- frontend/src/components/Common/CategoryStoreList/CategoryStoreList.tsx
- frontend/src/components/Common/CategoryStoreTab/CategoryStoreTab.tsx
- frontend/src/components/Rank/ProductRankingList/ProductRankingList.tsx
- frontend/src/components/Rank/RecipeRankingList/RecipeRankingList.tsx
- frontend/src/components/Rank/ReviewRankingList/ReviewRankingList.tsx
- frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
- frontend/src/components/Review/ReviewRegisterForm/ReviewRegisterForm.tsx
- frontend/src/hooks/common/index.ts
- frontend/src/hooks/common/useGA.ts
- frontend/src/hooks/search/useSearch.ts
- frontend/src/pages/HomePage.tsx
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/pages/ProductListPage.tsx
- frontend/src/pages/RecipePage.tsx
- frontend/src/utils/category.ts
- close #717 
- GA 이벤트 추가
- 상품 정렬, 리뷰 정렬, 리뷰 작성 버튼, 리뷰 등록
- 꿀조합 정렬, 작성 버튼, 등록
- 목록 페이지 카테고리 버튼
- 검색 페이지 검색
- 배너, 랭킹 등 링크로 되어있는 친구들은 이벤트 추가하지 않았습니다. 이벤트 등록을 하려면 button, navigate로 해야할 거 같아요. 이 부분에 대해서 의견주세요.!
- 더 추가해야할 이벤트 있다면 남겨주세요 😊
- 추정 시간 : 2시간
- 걸린 시간 : 1시간
> [FE] feat: GA 이벤트 추가

- backend/src/main/java/com/funeat/common/s3/S3Uploader.java
- close #686 
- 이미지 업로드 할 때 jpeg, png 만 가능했는데 webp 도 추가했습니다.
- 이미지 업로드 할 때 jpeg, png 만 가능했는데 webp 도 추가했습니다.
- x
- 추정 시간 : 0.1
- 걸린 시간 : 0.1
> [BE] feat: 이미지 업로드 확장자 추가

- backend/src/main/java/com/funeat/admin/presentation/AdminLoginController.java
- backend/src/main/java/com/funeat/admin/util/AdminCheckInterceptor.java
- close #750 
- Session 에 id, key를 따로 저장하는 방식으로 바꿨습니다.
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] hotfix: id, key Session 에 따로 저장

- frontend/src/pages/AuthPage.tsx
- frontend/src/pages/ProductDetailPage.tsx
- close #이슈번호
- 추정 시간 :
- 걸린 시간 :
> [FE] fix: 로컬스토리지 유틸 import 대소문자 수정

- frontend/src/components/Recipe/CommentList/CommentList.tsx
- frontend/src/hooks/queries/recipe/useInfiniteRecipeCommentQuery.ts
- close #이슈번호
- getNextPageParam에서 id를 접근하지 못하는 경우 처리
- ui에서도 댓글이 없을 때 텍스트 처리
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분
> [FE] feat: 꿀조합 댓글이 없는 경우 예외처리

- frontend/src/components/Recipe/CommentForm/CommentForm.tsx
- frontend/src/components/Recipe/CommentList/CommentList.tsx
- frontend/src/mocks/data/comments.json
- frontend/src/pages/RecipeDetailPage.tsx
- close #776
- 댓글 개수 totalElements로 수정
- 댓글 작성 후 가장 최신으로 올라가는 기능 추가
x
x
- 추정 시간 : 30분
- 걸린 시간 :
> [FE] feat: 꿀조합 댓글 버그 수정 및 개선

- backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
- backend/src/test/java/com/funeat/common/EventTest.java
- backend/src/test/java/com/funeat/fixture/ReviewFixture.java
- backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
- close #777 
- 기존에 통과했다 실패했다 하던 ReviewDeleteEventListenerTest 를 통과하도록 고쳤습니다.
- X
- X
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] fix: ReviewDeleteEventListenerTest 통과하도록 수정

- frontend/.storybook/preview-body.html
- frontend/src/components/Common/Svg/SvgIcon.tsx
- frontend/src/components/Common/Svg/SvgSprite.tsx
- frontend/src/components/Members/MemberRecipeList/MemberRecipeList.tsx
- frontend/src/components/Members/MemberReviewItem/MemberReviewItem.stories.tsx
- frontend/src/components/Members/MemberReviewItem/MemberReviewItem.tsx
- frontend/src/components/Members/MemberReviewList/MemberReviewList.tsx
- frontend/src/components/Members/index.ts
- frontend/src/hooks/queries/members/index.ts
- frontend/src/hooks/queries/members/useDeleteReview.ts
- frontend/src/mocks/handlers/memberHandlers.ts
- frontend/src/pages/MemberPage.tsx
- frontend/src/types/review.ts
- close #739 
- ReviewRankingItem과 MemberReviewItem 분리 (서로 디자인도 다르고 삭제 기능이 추가 되면서 로직이 달라짐)
- 마이페이지의 리뷰 목록에서 리뷰를 삭제할 수 있는 기능 추가
- 네이밍이랑 실수 없는지 봐주세요!
x
- 추정 시간 : 2시간
- 걸린 시간 : 1.5시간
> [FE] 리뷰 삭제 기능 구현

- frontend/src/components/Recipe/RecipeFavorite/RecipeFavorite.tsx
- frontend/src/components/Recipe/RecipeRegisterForm/RecipeRegisterForm.tsx
- frontend/src/components/Review/ReviewItem/ReviewItem.tsx
- frontend/src/hooks/queries/members/useLogoutMutation.ts
- frontend/src/hooks/search/useSearch.ts
- frontend/src/pages/MemberModifyPage.tsx
- close #785 
alert를 toast로 변경하였습니다.
x
x
- 추정 시간 : 1시간 
- 걸린 시간 : 5분
> [FE] refactor: alert를 toast로 변경

- backend/src/test/java/com/funeat/review/application/ReviewDeleteEventListenerTest.java
- close #787 
ReviewDeleteEventListenerTest의
`리뷰_삭제가_정상적으로_커밋되었지만_이미지가_존재하지_않으면_이미지_삭제_로직이_작동하지않는다()` 테스트가
테스트 환경에 따라 성공 실패 번갈아 발생
- 로컬에서 성공
- 깃허브액션에서 성공
- 젠킨스 빌드시 성공 실패 번갈아 발생
실패하는 이유 추정 1
- reviewDeleteEventListener의 deleteReviewImageInS3는 비동기로 동작
- 테스트 실행 환경(스레드 개수?)에 따라 전 테스트에서 사용된 이벤트가 다음 테스트에서 잡히는 경우 생김
- ""인 이미지를 가지는 event를 사용하는 테스트에서 자꾸 "test3" 이미지(전 테스트에서 사용되는 이미지)를 가지는 event가 잡힘 -> ""여서 작동하지 않아야 하는 delete 메소드가 "test3"을 읽고 작동 -> 실패
- 해결 시도: 테스트 이후 event 비워주기 events.clear()
=> 근데 젠킨스에서 가끔 실패하는 것으로 보아 아닌듯 ..
실패하는 이유 추정 2
- events.clear로 event를 비워주더라도 이미 앞 테스트에서 uploader.delete는 비동기적으로 작동되었기 때문에 delete 작동 여부 검증에 걸리는듯
정확한 이유는 젠킨스 브랜치 매핑 따로 해서 로그 하나하나 찍어봐야 할 것 같은데
당장 내일 운영 배포해야하기 때문에.. 우선 테스트 삭제 결정
- X
- 비동기를 통합테스트하는게 맞을까?
- 그냥 1) service에서 event 발행하는지 2) eventlistener의 …
> [BE] test: 테스트 환경에 영향받는 비동기 로직 작동 검증 테스트 제거

- frontend/src/hooks/queries/review/useReviewDetailQuery.ts
- frontend/src/mocks/data/reviewDetail.json
- frontend/src/pages/ReviewDetailPage.tsx
- frontend/src/router/index.tsx
- frontend/src/types/response.ts
- close #794
리뷰 상세의 api를 수정하고 router의 위치를 바꾸었습니다.
x
x
> [FE] fix: 리뷰 상세 api 수정

- backend/src/main/resources/application.yml
- close #793
- HikariCP 옵션 설정 (`connection-timeout`, `maximum-pool-size`)
- x
- x
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] feat: HikariCP 옵션 설정

- frontend/src/apis/index.ts
- frontend/src/components/Common/Banner/Banner.tsx
- frontend/src/components/Common/index.ts
- frontend/src/hooks/queries/banner/index.ts
- frontend/src/hooks/queries/banner/useBannerQuery.ts
- frontend/src/mocks/browser.ts
- frontend/src/mocks/data/banners.json
- frontend/src/mocks/handlers/bannerHandlers.ts
- frontend/src/mocks/handlers/index.ts
- frontend/src/pages/HomePage.tsx
- frontend/src/types/banner.ts
- close #764 
- 배너 조회 API 연결
- 배너 컴포넌트 작성
x
- 랜덤으로 하나의 이미지를 보이게 했습니다
- 추정 시간 : 2시간
- 걸린 시간 : 30분
> [FE] feat: 배너 조회 API 연결 및 배너 컴포넌트 작성

- frontend/src/router/index.tsx
- close #이슈번호
- RecipeDetail 페이지를 AuthLayout 아래로 이동
- 각 router layout에 주석 작성
x
x
- 추정 시간 : 10분
- 걸린 시간 : 10분
> [FE] router 리팩터링

- backend/src/main/java/com/funeat/product/application/ProductService.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/product/dto/ProductResponse.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/test/java/com/funeat/product/domain/ProductTest.java
- backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
- close #797 
- 리뷰 삭제시 상품 속 (반정규화된) 리뷰 관련 데이터 갱신 로직 추가
- averageRating
- reviewCount
- 상품 상세 조회시 count 쿼리 날리는 대신 reviewCount 사용하도록 수정
- X
- X
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] feat: 리뷰 삭제시 상품 정보 업데이트 로직 추가

- backend/src/main/java/com/funeat/review/application/ReviewService.java
- close #813
- 리뷰 삭제시 썸네일 업데이트가 제대로 되지 않는 문제 해결
- X
- X
- 추정 시간 : 0.5
- 걸린 시간 : 0.5
> [BE] fix: 상품의 썸네일이었던 리뷰를 삭제했을 경우 썸네일이 업데이트 되지 않는 문제 해결

- frontend/src/constants/index.ts
- frontend/src/mocks/handlers/recipeHandlers.ts
- frontend/src/pages/AuthPage.tsx
- frontend/src/pages/ProductDetailPage.tsx
- frontend/src/pages/RecipePage.tsx
- close #809 
- 꿀조합 페이지 접속 시 이전 페이지 로컬스토리지에 경로 저장
- 로그인 안 하고 꿀조합 상세로 갔을 때 그 경로를 가져올 수 없어 바로 상세로 리다이렉트 불가
- 그래서 꿀조합 목록 페이지로 이동하게 했습니다
- 기존 상품 경로 저장처럼 로컬스토리지에 저장, 그래서 이름을 PRODUCT_PATH -> PREVIOUS_PATH로 수정
- 로컬에서 확인이 안 됨... 데브에서 한 번 보시죠. 로직 수정된건 없습니다!
- 추정 시간 :
- 걸린 시간 :
> [FE] feat: 꿀조합 페이지 접속 시 이전 페이지 로컬스토리지에 경로 저장

- backend/src/main/java/com/funeat/product/domain/Category.java
- backend/src/main/java/com/funeat/product/domain/Product.java
- backend/src/main/java/com/funeat/review/application/ReviewService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/test/resources/application.yml
- close #817 
- 상품에 이미지가 있는 리뷰가 없을 경우 기본 이미지로 업데이트 하도록 수정
- X
- 무중단 배포 이슈 관련해서 actuator의 server port 옵션도 제거했습니다.
- 추정 시간 : 1
- 걸린 시간 : 1
> [BE] fix: 상품에 이미지가 있는 리뷰가 없을 경우 기본 이미지로 설정

- backend/src/test/java/com/funeat/acceptance/auth/LoginSteps.java
- backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
- backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
- backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
- backend/src/test/resources/application.yml
- close #759
- 프로덕션 코드와 똑같이 로그인 테스트 쿠키 이름도 `SESSION`으로 변경합니다.
- x
- x
- 추정 시간 : 0.0000001
- 걸린 시간 : 0.00000000001
> [BE] refactor: 프로덕션 로그인 쿠키 이름과 테스트 로그인 쿠키 이름 통일

- frontend/src/components/Product/ProductDetailItem/ProductDetailItem.tsx
- frontend/src/components/Product/ProductItem/ProductItem.tsx
- frontend/src/mocks/data/pbProducts.json
- close #816 
- PB 상품 목록에서 상품 썸네일 삼김이로 변경
- 추정 시간 :
- 걸린 시간 :
> [FE] feat: PB 상품 목록에서 상품 썸네일 삼김이로 변경
